thymikee/jest-preset-angular

jest-preset.json

The path `src/tsconfig.json` does [not exist](https://github.com/angular/angular-cli/tree/master/packages/%40angular/cli/blueprints/ng/files/__path__) anymore in an app created by Angular CLI. 
It has changed to `src/tsconfig.app.json` resulting in the error below when trying to follow the installation steps described in the blog post. 
```
FAIL  src/app/app.component.spec.ts
● Test suite failed to run
ENOENT: no such file or directory, open '/path/to/angular-cli-jest/src/tsconfig.json'
```

Change default tsconfig.json path to src/tsconfig.app.json

---

jest-preset.json

Allow all folders within src for module resolution

---

.npmignore
__tests__/preprocessor.test.js
circle.yml
package.json
preprocessor.js
yarn.lock

**Summary**
Broader regex for `styleUrls` handling.
Fixes https://github.com/thymikee/jest-preset-angular/issues/9.
**Test plan**
Test cases I used:
```js
@Component({
selector: 'xc-media-box-h0',
templateUrl: './media-box-h0.component.html',
styleUrls: [ '../media-box.component.scss' ],
})
@Component({
selector: 'xc-media-box-h0',
templateUrl: './media-box-h0.component.html',
styleUrls: ['../media-box.component.scss',
'./media-box-h0.component.scss'],
})
@Component({
selector: 'xc-media-box-h0',
templateUrl: './media-box-h0.component.html',
styleUrls: [
'../media-box.component.scss',
],
})
@Component({
selector: 'xc-media-box-h0',
templateUrl: './media-box-h0.component.html',
styleUrls: [
'../media-box.component.scss',
'./media-box-h0.component.scss'
],
})
```

Overhaul regex for styleUrls

---

README.md
setupJest.js

**Summary**
Removes `rxjs` import, because it's an anti-pattern to do so, and also it degrades tests performance.
Fixes #17

Remove rxjs from default imports

---

HTMLElementPlugin.js
angular-snapshot.js
circle.yml
example/src/app/__snapshots__/app.component.spec.ts.snap
example/src/app/app.component.html
example/src/app/app.component.spec.ts
example/src/app/app.component.ts
example/src/app/calc/__snapshots__/calc.component.spec.ts.snap
example/src/app/calc/calc.component.html
example/src/app/calc/calc.component.spec.ts
example/src/app/calc/calc.component.ts
package.json
setupJest.js

Snapshots support

---

__tests__/preprocessor.test.js
preprocessor.js

Fixed template preprocessor regex to retain "./" correctly.  For instance, previously it would replace "./mytemplate.html" with "././mytemplate.html".  Now it works as follows:
templateUrl: './component.html' => template: require('./component.html')
templateUrl: 'component2.html' => template: require('./component.html')
templateUrl: '../component2.html' => template: require('./../component.html')
templateUrl: '../../component2.html' => template: require('./../../component.html')
templateUrl: 'test/component2.html' => template: require('./test/component.html')
templateUrl: './test/component2.html' => template: require('./test/component.html')

Template preprocessor path fix

---

__tests__/preprocessor.test.js
example/src/app/__snapshots__/app.component.spec.ts.snap
example/src/app/app.component.html
example/src/app/app.component.spec.ts
example/src/app/app.component.ts
preprocessor.js
yarn.lock

**Summary**
During preprocessing, preset is wrapping HTML into a template literal. This caused bugs, when `${` or backtick (\`) was used inside HTML template, which are valid chars in Angular-land.
As a workaround these special characters are now escaped.
**Test plan**
Enhanced example

Preprocessor improvements

---

README.md
__tests__/preprocessor.test.js
jest-preset.json
package.json
yarn.lock

ts-jest 20.0.7 has deprecated the __TS_CONFIG__ global parameter, with a new 
"ts-jest": {
"tsConfigFile": "src/tsconfig.spec.json"
}
The PR fixes the preset, tests and readme to support this.

__TS_CONFIG__ deprecation fixes

---

README.md

FYI @thymikee @DorianGrey
Did I write everything correct?
Sorry for possible mistakes (English is not my native language😿 ).

Add section to troubleshooting about JS files transpiling

---

jest-preset.json

If you use the jest-preset-angular for an ionic project, there they have an app.ts, and the moduleNameMapper maps it to an incorrect location.

be a bit more specific with the moduleNameMapper regexps

---

jest-preset.json
package.json
testEnvironment.js
yarn.lock

Partially resolves #51 and gives us flexibility of having newer version of JSDOM, which is needed to use browser version of `zone.js` (see https://github.com/thymikee/jest-preset-angular/issues/65#issuecomment-333404988)

Add custom environment

---

testEnvironment.js

In order to fix Angular Material tests, a default HTML shell should be used
This change fixes the following console warnings
```shell
PASS  src/client/app/+admin/admin.component.spec.ts
● Console
console.warn node_modules/@angular/material/bundles/material.umd.js:206
Current document does not have a doctype. This may cause some Angular Material components not to behave as expected.
console.warn node_modules/@angular/material/bundles/material.umd.js:206
Current document does not have a doctype. This may cause some Angular Material components not to behave as expected.
```

add default html to test environment

---

AngularSnapshotSerializer.js

I was seeing some strange behavior popping up, where `node` was `undefined` for some of my components, which was errors being thrown about `hasOwnProperty` being called on `undefined`.
I don't really know a whole lot about the internals of Angular components, however, I did recently upgrade to Angular 5 so I suspect this might have something to do with that.
Inspecting the `val.componentRef._view.nodes` shows me that there are in fact multiple nodes in the array, and one is `undefined`. I tried simplifying my template down to a single `<div></div>`, but no luck.
All the tests are passing, but please let me know if there are any red flags around this sort of change.

Protect against potentially undefined nodes.

---

CHANGELOG.md
example/package.json
package.json
yarn.lock

Upgrade Jest to 22.1.x. Jest 22.1.x offers some new small features, no breaking changes

Upgrade Jest to 22.1.x

---

jest-preset.json
setupJest.js

Move serializers setup to jest config to be possible to override them

---

CHANGELOG.md
jest-preset.json
package.json
yarn.lock

ts-jest just released their new package version which removes `mapCoverage` to be in sync with Jest. I think it's time for us to be in sync with them too.

Upgrade package dependencies

---

CHANGELOG.md
README.md
jest-preset.json

Jest default set up testMatch to get all the test files to run. Removing testRegex out of the preset will bring flexibility to the users to set up their own testMatch/testRegex.

Remove testRegex out of preset

---

__tests__/tsconfig.spec.json
package.json
preprocessor.js
yarn.lock

- Upgrade `ts-jest` to 23.0.1
- Upgrade `@types/jest` to 23.3.0
- Upgrade devDependencies for `jest`
I noticed that relative path resolving for `tsconfig` seems to be broken by `ts-jest`. I'm not sure if we should wait for them to fix that issue before we can release 6.0

Upgrade ts-jest, @types/jest

---

__tests__/preprocessor.test.js
preprocessor.js

As explained in readme, the current approach to processing `templateUrl` is a scrappy regex. However, the current regex only supports single quote and double quote.
This PR add backtick support to it.

support backtick quoted templateUrl

---

example/src/app/app.module.ts
example/src/app/heroes/heroes.component.css
example/src/app/heroes/heroes.component.html
example/src/app/heroes/heroes.component.spec.ts
example/src/app/heroes/heroes.component.ts
example/src/app/service/hero.service.spec.ts
example/src/app/service/hero.service.ts
example/tslint.json

Related to Issue #110
An example of how to mock a service provider's return values using `jest.fn()` and rxjs' `Subject` without having to bother with mocking low-level HTTP responses. 
I placed the component in its own `heroes` folder which is kind of awkward since the Hero model and service are in the more generic `service` folder, but I didn't want to take too many liberties in moving stuff around.  
Other small changes:
* Removed `'rxjs'` from the import-blacklist as it was causing linter warnings on existing code.
* Fixed incorrect describe name on existing HeroService spec.

Add HeroesComponent example with mocked service provider (#110)

---

example/package.json
example/yarn.lock

This change makes the example properly test the local preset instead of published version.
cc @wtho

chore: use local preset from example app

---

CHANGELOG.md

- Highlighting BREAKING text.
- Change `Adjustment` to `Chore` to keep consistency of CHANGELOG template.

Adjust CHANGELOG for next release (v7)

---

README.md
__tests__/InlineHtmlStripStylesTransformer.test.ts
__tests__/__snapshots__/InlineHtmlStripStylesTransformer.test.ts.snap
package.json
src/InlineHtmlStripStylesTransformer.ts
yarn.lock

Closes #210
* Transformer became more simple
* Test was added to verify `templateUrl` gets transformed e. g. in `*.spec.ts` outside a decorator
* Updated the *Preprocessor*-section in `README.md`
:exclamation: Note that it seems the transformer was modified a lot, but basically I just removed code that only looked deep inside decorators. Now it checks everywhere for `stlyes`, `styleUrls` and `templateUrl`.

Transform templateUrl, styleUrls and styles everywhere

---

README.md

It is not yet documented in `ts-jest`, but it [does use `require.resolve`](https://github.com/kulshekhar/ts-jest/blob/90beca89b875e947e55fc9774d10493773cbae41/src/config/config-set.ts#L711), which allows us to specify the node module following the file path.
Adding this information will prevent issues such as #217.
Fixes #217

docs: add astTransformers in configuration example

---

package.json
yarn.lock

This resolves an issue where constructor parameters are considered code branches and are not covered by code coverage. https://github.com/istanbuljs/istanbuljs/issues/70

upgrade ts-jest version

---

CHANGELOG.md
README.md
example/package.json
example/src/jestGlobalMocks.ts
example/yarn.lock
jest-preset.js
package.json
yarn.lock

This PR introduces jsdom v13 as default test environment for jest-preset-angular. This is achieved by
* Adding [jest-environment-jsdom-thirteen](https://github.com/theneva/jest-environment-jsdom-thirteen) as dependency
* Adding `testEnvironment: 'jest-environment-jsdom-thirteen' to `jest-preset.js`
* Removing Web Storage API mocks from `example/jestGlobalmocks.ts`
* Adding instructions in README Troubleshooting to configure usage of jsdom v11 (one line in jest configuration)
I added tests in a second commit to confirm it works, but I think they do not have to end up in the repository, as they basically test, what is already tested in jsdom itself.
Closes #216

feat: jsdom-v13

---

README.md

Related to thymikee/jest-preset-angular#64

docs: do not use .babelrc file but rather babel.config.js

---

.gitignore
README.md
example/package.json
example/src/app/app.component.spec.ts
example/yarn.lock
jest-preset.js
package.json
yarn.lock
zone-patch/index.js

This is a PoC. Jest 24 works without any changes from our side. It added some defaults to TS but we use slightly different ones (e.g. no `.tsx`).
However, until `ts-jest` updates, we'll likely need to hold off with the upgrade, because of peer dep warnings.
Fixes #223

feat: Jest 24

---

CHANGELOG.md

Fix typo: `astTransformer` ➡️ `astTransformers`

Fix typo in migration guide

---

README.md

* jest-zone-patch is embeded (#214) as a dependency and should not be mentioned as being installed at the same time as this package is not found in package.json, package-lock.json or yarn.lock - and can be presumed missing.
* @types/jest might not be installed so install it explicitly
* Specify how to avoid karma conflicts (ref #233)
- Otherwise consumers might get `TypeError: Cannot read property 'prototype' of undefined` while jest processes new angular cli projects

📝 Improve docs

---

__tests__/CoreJS-es6-reflect.test.ts
__tests__/CoreJS-es7-reflect.test.ts
__tests__/tsconfig.spec.json
example/package.json
example/yarn.lock
package.json
setupJest.js
yarn.lock

fix(package): update core-js to version 3.0.0

---

README.md

Updated several outdated parts in the README.md, mostly in the FAQ section:
* `jest-zone-patch` is included directly in the preset now
* `preserveWhitespaces` is also `false` in Angular v7 (https://angular.io/api/core/Component#preserveWhitespaces)
* `body.style.transform`-property is available in the currently used JSDOM version (v13), patching is not required anymore.
* Transpiling with babel-jest recommended to complement the ts-jest configuration in an outdated style. Updated it to the current one.
* We should not recommend patching RxJS the v5 way, RxJS v6 is an Angular dependency since Angular v6. I added a note to make this clear. Maybe we should remove this part completely in a later version.

chore: bring outdated information up-to-date

---

.gitignore
CHANGELOG.md
__tests__/InlineFilesTransformer.test.ts
__tests__/StripStylesTransformer.test.ts
__tests__/__snapshots__/InlineFilesTransformer.test.ts.snap
__tests__/__snapshots__/StripStylesTransformer.test.ts.snap
jest-preset.js
src/InlineFilesTransformer.ts
src/StripStylesTransformer.ts
src/TransformUtils.ts

This PR is another implementation change in the transformation behavior. It is a proposal and open for discussion.
See #254 
Until now we transformed 'templateUrl', 'styleUrls' and 'styles'
everywhere they were assigned.
This even transformed code like this:
`console.log({ styles: {...}})` => `console.log({ styles: [] })`
The new implementation of the AstTransformer only transforms property
assignments to 'styles' if it is placed inside a decorator.
`templateUrl` and `styleUrls` are still transformed everywhere if assigned to a string, as Angular might expect them to be an actual Angular-Template or CSS code. This will crash the tests, if they are passed to the `@Component` decorator.
A new unit test explains the new implementation:
Untransformed:
```ts
const assignmentsToNotBeTransformed …
```

feat: transform 'styles' only in decorator

---

README.md

Closes #312
The message can be hidden on npm by using templates, or a quick `prepublish` script that runs an `sed` command (or equivalent) so it shows up on Github only.

docs: add a warning message for exposed config

---

CHANGELOG.md
README.md
example/yarn.lock
jest-preset.js
package.json
yarn.lock

* update default jsdom enviroment to v15
* enable AngularNoNgAttributesSnapshotSerializer by default
* use better reference of astTransformers (always in preset instead of
relative) to avoid user confusion in README

chore: jsdom15 and enable AngularNoNgAttributesSnapshotSerializer by default

---

.circleci/config.yml

To avoid a new issue created by greenkeeper for each failing dependency update (like e. g. #250), the `greenkeeper-update-lockfile` program is used to handle the udpate in CI environments.
The [greenkeeper lockfile](https://github.com/greenkeeperio/greenkeeper-lockfile#circleci-workflows) documentation was followed to fix this. No changes on the codebase itself are necessary.

ci(greenkeeper): greenkeeper update lockfile

---

example/src/app/app.component.spec.ts
example/src/app/service/hero.service.spec.ts
example/src/app/simple/another.component.ts
example/src/app/simple/simple.component.spec.ts
src/zone-patch/index.js

Close #339.
Fix `test.each` not in ProxyZone issue.
Also remove some not needed assignment.
And I will try to move this source into `angular/zone.js` repo, and also add support to timer methods such as `jest.fakeTimers/jest.runAllTicks`, after that `jest-preset-angular` can just import `zone-testing` bundle.
@thymikee , please help to check this one, thank you!

fix: test.each should be in ProxyZone

---

README.md

I've added documentation to the Troubleshooting section to provide some guidance on the use of the `emitDecoratorMetadata` compiler option for Angular 8 users as described in issue #288
- [X ] I added the documentation in `README.md`

emitDecoratorMetadata Documentation for issue 288

---

example/src/app/app.component.spec.ts
src/zone-patch/index.js

in the pervious PR #340, zone.js add support to jest test.each methods, but it
introduces a bug, which is the `done()` function will not be handled correctly.
```
it('should work with done', done => {
// done will be undefined.
});
```
The reason is the logic of monkey patching `test` method changed from
```
return testBody.length === 0
? () => testProxyZone.run(testBody, null)
: done => testProxyZone.run(testBody, null, [done]);
```
to
```
return function(...args) {
return testProxyZone.run(testBody, null, args);
};
```
the purpose of this change is to handle the following cases.
```
test.each([1, 2])('test.each', (arg1, arg2) => {
expect(arg1).toBe(1);
expect(arg2).toBe(2);
});
```
so in jest, it is a little complex, because the `testBody`'s parameter may be bigger than 1, so the …

fix: zone.js patch jest should handle done correctly

---

example/src/app/app.component.spec.ts
src/zone-patch/index.js

refactor the zone.js patch test method logic to handle all cases
1. each with args
2. each with args and done
3. each with template string
4. each with template string and done
Close #359.

fix: refactor zone patch test method

---

example/package.json
example/src/app/__snapshots__/app.component.spec.ts.snap
example/src/app/app.component.spec.ts
example/src/app/calc/__snapshots__/calc.component.spec.ts.snap
example/src/app/medium/__snapshots__/medium.component.spec.ts.snap
example/src/app/ng-reflect-as-text/__snapshots__/ng-reflect-as-text.component.spec.ts.snap
example/src/app/on-push/__snapshots__/on-push.component.spec.ts.snap
example/src/app/simple-with-styles/__snapshots__/simple-with-styles.component.spec.ts.snap
example/src/app/simple/__snapshots__/simple.component.spec.ts.snap
example/yarn.lock
src/AngularSnapshotSerializer.js

Closes: #351 
| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

feat: make `AngularSnapshotSerializer` compatible with Ivy

---

CHANGELOG.md
example/src/app/__snapshots__/app.component.spec.ts.snap
example/src/app/app.component.html
src/AngularNoNgAttributesSnapshotSerializer.js

Adds in filtering for contents of attributes as proposed in #336 (thanks for the sample code @ravishivt !)
Fixes #336 
Tested by adding into storyshots tests for my company, but additional automated testing would be great. Please advise on what I should do for that. Sample from one of the tests:
Update: the example app snapshot test verifies this functionality.
| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |
(assuming the other serializer code works, this should too)

Merge in class filtering solution from issue 336

---

src/utils/reflect-metadata.ts

I recently learned about weakmaps and why using them is a much better approach to store metadata about an object than to store it as a property on that object itself.
I realized I once introduced the wrong approach in jest-preset-angular and now want to fix this.
Also I removed most `any` in `reflect-metadata` and added more typings.

feat: replace type property with weakmap

---

package.json
src/__tests__/__snapshots__/ng-jest-config.spec.ts.snap
src/__tests__/ng-jest-config.spec.ts
src/__tests__/tsconfig-ve.json
src/__tests__/tsconfig.json
src/config/ng-jest-config.ts
yarn.lock

Introduce `NgJestConfig` which extends `ts-jest` config class `ConfigSet`. In this class, we override `readTsConfig` to use `readConfiguration` from `@angular-compiler/cli` to retrieve tsconfig options as well as Angular compiler options.
For now, this class isn't used anywhere. The plan is use it after #526 is merged.
Added unit tests, green CI
**N.A.**

refactor(config): use `readConfiguration` from `@angular/compiler-cli`

---

jest-preset.js
package.json

Jest 27 sets default test environment to `node`, see https://github.com/facebook/jest/pull/9874. Since we need `jsdom` so we need to explicitly set it in `jest-preset.js`.
Jest 27 will still bundle `jest-environment-jsdom` in the main package and Jest 28 will separate them. However, we should just go ahead and set explicitly `jest-environment-jsdom` in our dependencies list.
More information see https://jestjs.io/blog/2020/05/05/jest-26
Green CI
**N.A>**

refactor(preset): explicitly define `jsdom` for test environment

---

package.json

Angular 8 support policy ended on 28th Nov 2020
`jest-preset-angular` now requires Angular 9+. If you are using Angular 8, please use **v8.3.2**
**N.A.**

chore: drop support for Angular 8

---

README.md
e2e/test-app-v10-zone-v11/jest.config.js
e2e/test-app-v10/jest.config.js
e2e/test-app-v9/jest.config.js
ngcc-jest-processor.js
scripts/e2e.js
src/utils/ngcc-jest-processor.ts

Separate from #562 
Users can add this script to their jest config
```
require('jest-preset-angular/ngcc-jest-processor');
module.exports = {
// jest config options
}
```
so that jest will always run `ngcc` before test
e2e tests run this script
**N.A.**

feat(utils): add `ngcc-jest-processor` util script

---

README.md
e2e/test-app-v10-zone-v11/package.json
e2e/test-app-v10/package.json
e2e/test-app-v10/src/app/dynamic-component/dynamic-button.component.ts
e2e/test-app-v10/src/app/dynamic-component/dynamic-host.component.spec.ts
e2e/test-app-v10/src/app/dynamic-component/dynamic-host.component.ts
e2e/test-app-v10/src/app/dynamic-component/dynamic-host.module.ts
e2e/test-app-v9/package.json
e2e/test-app-v9/src/app/on-push/on-push.component.spec.ts
package.json
yarn.lock

Separate from #562 
Green CI
**N.A.**

test(e2e): add entry component example with Ivy

---

src/__tests__/__snapshots__/ng-jest-config.spec.ts.snap
src/__tests__/ng-jest-config.spec.ts
src/config/ng-jest-config.ts

Set `skipLibCheck: true` if not defined in tsconfig. This will improve slightly performance
Updated unit tests, green CI
By default, `skipLibCheck` is `true` if not defined in tsconfig. If one wants to have it as `false`, one can define it explicitly in tsconfig
**N.A.**

perf(config): set `skipLibCheck: true` if not defined in tsconfig

---

src/__tests__/index.spec.ts
src/__tests__/ng-jest-compiler.spec.ts
src/compiler/compiler-host.ts
src/compiler/ng-jest-compiler.ts
src/index.ts

Reuse Jest `cacheFS` when reading files for compiler
Green CI
**N.A.**

perf(compiler): reuse `cacheFS` from jest to reduce file system reading

---

e2e/test-app-v10/jest-esm-uniso.config.js
e2e/test-app-v10/package.json
e2e/test-app-v11/jest-esm-uniso.config.js
e2e/test-app-v11/package.json
e2e/test-app-v9/jest-esm-uniso.config.js
e2e/test-app-v9/package.json
scripts/e2e.js
src/__tests__/__snapshots__/ng-jest-compiler.spec.ts.snap
src/__tests__/__snapshots__/replace-resources.spec.ts.snap
src/__tests__/ng-jest-compiler.spec.ts
src/compiler/ng-jest-compiler.ts

Add support ESM for `isolatedModules: false`
- Make sure `esModuleInterop` and `allowSyntheticDefaultImports` true to support import CJS into ESM
- Adjust `module` value correctly according to Jest transform option `supportsStaticESM` and `ts-jest` config `useESM`
Related to #710 
- Added unit tests
- Added jest config for `isolatedModules: false` with ESM and run e2e tests with this config
Green CI
**N.A.**

feat(compiler): support ESM for `isolatedModules: false`

---

src/__tests__/__snapshots__/ng-jest-compiler.spec.ts.snap
src/__tests__/ng-jest-compiler.spec.ts
src/compiler/ng-jest-compiler.ts

Previously `SourceFile.text` was the old contents of the file - the state of the file during startup. This change updates the SourceFile text so that emit() receives the changed file contents.
fixes: #764 
I've tested this locally by copying the `build` dir into node_modules on 2 different projects (test repo and production repo) and verified. It would be ideal to create a unit test for this, but I'm not sure I'm up to that.

fix(watch mode): update SourceFile with fileContent

---

presets/index.d.ts
presets/index.js
src/__tests__/__snapshots__/ng-jest-config.spec.ts.snap
src/__tests__/__snapshots__/presets.spec.ts.snap
src/__tests__/presets.spec.ts
tsconfig.spec.json

Add type definition for `presets` entry point
Added unit test, green CI
**N.A.**

feat(presets): add type definition for `presets` entry point

---

commitlint.config.js
e2e/test-app-v10/setup-jest.ts
e2e/test-app-v11/setup-jest.ts
e2e/test-app-v9/setup-jest.ts
index.js
package.json
scripts/e2e.js
setup-jest.js
yarn.lock

**DEPRECATION**
Import setup file via `import 'jest-preset-angular'` is deprecated in favor of `import 'jest-preset-angular/setup-jest'`
Green CI
**N.A.**

refactor(config): deprecate import setup file from `index.js`

---

jest-preset.js
package.json
src/AngularSnapshotSerializer.js
src/HTMLCommentSerializer.js
src/serializers/html-comment.ts
src/serializers/index.ts
src/serializers/ng-snapshot.ts
src/serializers/no-ng-attributes.ts
yarn.lock

DEPRECATION
- Import serializer via `'jest-preset-angular/build/AngularNoNgAttributesSnapshotSerializer.js'` is deprecated in favor of `'jest-preset-angular/build/serializers/no-ng-attributes'`
- Import serializer via `'jest-preset-angular/build/AngularSnapshotSerializer.js'` is deprecated in favor of `'jest-preset-angular/build/serializers/ng-snapshot'`
- Import serializer via `'jest-preset-angular/build/HTMLCommentSerializer.js'` is deprecated in favor of `'jest-preset-angular/build/serializers/html-comment'`
Green CI
**N.A.**

refactor(config): deprecate import serializer paths

---

e2e/__tests__/ast-transformers.test.ts
examples/test-app-v10/package.json
examples/test-app-v11/package.json
examples/test-app-v9/package.json
src/transformers/replace-resources.ts

TypeScript provides a set of  pure  functions for producing syntax tree nodes. Since TypeScript 4.0 these methods have been deprecated in favor of the `factory` API.
See: https://github.com/microsoft/TypeScript/wiki/API-Breaking-Changes#typescript-40
This PR replaces deprecated TypeScript method for `replace-resources` AST transformer. `downlevel-ctor` will be in another PR.
Green CI
**N.A.**

refactor(transformers): replace deprecated TypeScript methods for `replace-resources` AST transformer

---

presets/index.js
src/__tests__/__snapshots__/jest-preset.spec.ts.snap
website/docs/getting-started/options.md
website/docs/guides/absolute-imports.md

Remove `moduleNameMapper` config from both presets, CJS and ESM
Closes #908 
Green CI
When generating a new project from Angular CLI, by default the `tsconfig.json` doesn't contain any path mappings hence removing `moduleNameMapper` from preset will make sure that the preset works in pair with `tsconfig.json`.
Ones who are relying on the value of `moduleNameMapper` from the preset should create their own `moduleNameMapper` config manually or via `ts-jest` util https://kulshekhar.github.io/ts-jest/docs/getting-started/paths-mapping
**N.A.**

fix(presets): remove `moduleNameMapper` config

---

.github/workflows/nodejs.yml
examples/example-app-v10/package-lock.json
examples/example-app-v10/package.json
examples/example-app-v11/package-lock.json
examples/example-app-v11/package.json
examples/example-app-v12-monorepo/jest-esm.config.js
examples/example-app-v12-monorepo/jest.config.js
examples/example-app-v12-monorepo/package-lock.json
examples/example-app-v12-monorepo/package.json
examples/example-app-v12-monorepo/projects/app1/jest.config.js
examples/example-app-v12-monorepo/projects/app2/jest-esm.config.js
examples/example-app-v12-monorepo/projects/app2/jest.config.js
examples/example-app-v12-monorepo/projects/app2/tsconfig-esm.spec.json
examples/example-app-v12/package-lock.json
examples/example-app-v12/package.json
examples/example-app-v9/package-lock.json
examples/example-app-v9/package.json
package.json
scripts/upgrade-examples-deps.js

See https://github.com/thymikee/jest-preset-angular/issues/941#issuecomment-854580348
See https://github.com/ahnpnl/jest-preset-angular/actions/runs/902838031
**N.A.**

fix: revert `exports` in `package.json`

---

.github/workflows/nodejs.yml

Angular 12 now allows Node 15 and 16 so we can reenable them for CI
Green CI
**N.A.**

build: reenable Node 15 and 16 for CI

---

package.json
yarn.lock

When installing `jest-preset-angular` with angular 12.0.3, two webpack versions are installed in node_modules:
- webpack `5.36.2` from `jest-preset-angular`
- webapck `5.38.1` from `@angular-devkit/build-angular`
This PR widens the range of the optional `webpack` dependency, so the package manager can deduplicate the webpack version. This will result in faster install times and smaller node_modules folder.
All tests are green.

fix: widen range for optional webpack dependency

---

website/docs/getting-started/presets.md
website/docs/guides/esm-support.md
website/versioned_docs/version-9.x/getting-started/presets.md
website/versioned_docs/version-9.x/guides/esm-support.md

There is a typo in the docs. It says `jest-preset-angular/presets/default-esm` everywhere, and it should say `jest-preset-angular/presets/defaults-esm` (note the **s** in **defaults**).
The tests are OK, though. It's just a problem in the docs.

docs: fix typo in preset name

---

website/docs/guides/using-with-babel.md
website/versioned_docs/version-9.x/guides/using-with-babel.md

I was running into issues using ts-jest in my transform configuration and ahnpnl pointed out that since version 9.0.0 we need to use jest-preset-angular instead. I noticed in the documentation here: https://thymikee.github.io/jest-preset-angular/docs/guides/using-with-babel that it states version 9.X at the top but still seems to be referencing ts-jest in the transform configuration. Seems like it should be updated to show jest-preset-angular instead.
- [ X] No
Simple documentation change.

since version 9.0.0 we need to use jest-preset-angular instead of ts-jest in the transform configuration

---

examples/example-app-v10/tsconfig-esm.spec.json
examples/example-app-v11/tsconfig-esm.spec.json
examples/example-app-v12-monorepo/projects/app1/tsconfig-esm.spec.json
examples/example-app-v12-monorepo/projects/app2/tsconfig-esm.spec.json
examples/example-app-v12/tsconfig-esm.spec.json
examples/example-app-v9/tsconfig-esm.spec.json
src/__tests__/ng-jest-config.spec.ts
src/__tests__/ng-jest-transformer.spec.ts
src/config/ng-jest-config.ts
src/ng-jest-transformer.ts
tsconfig.spec.json

Closes #974
Updated unit tests and e2e tests
**N.A.**

fix(config): set `allowJs: true` internally always

---

src/utils/ngcc-jest-processor.ts

Add an extra check on the existence of `@angular/core` package to `ngcc-jest-processor` util script and throw error when `@angular/core` is not found. This will help users to know if `ngcc` is invoked correctly or not.
Green CI
**N.A.**

fix(utils): throw error when cannot find `@angular/core` for `ngcc` util script

---

presets/index.js
src/__tests__/__mocks__/icon.component.svg
src/__tests__/__mocks__/icon.component.ts
src/__tests__/__snapshots__/jest-preset.spec.ts.snap
src/__tests__/__snapshots__/replace-resources.spec.ts.snap
src/__tests__/replace-resources.spec.ts
website/docs/getting-started/options.md
website/versioned_docs/version-9.x/getting-started/options.md

See issue: https://github.com/thymikee/jest-preset-angular/issues/1055
Honnestly, I am not quite sure hom to test that feature using jest.
I can add a svg file in the examples but I am not sure it would count as proper testing.

feat: add support for svg templates

---

e2e/jest.config.js
e2e/path-mapping/__tests__/path-mapping.ts
e2e/transform-mjs/__tests__/transform-mjs.ts
e2e/transform-mjs/foo.mjs
e2e/transform-mjs/jest.config.js
package.json
src/__tests__/__snapshots__/ng-jest-transformer.spec.ts.snap
src/__tests__/ng-jest-transformer.spec.ts
src/ng-jest-transformer.ts
yarn.lock

**With esbuild on Linux Node 12 no Jest cache**
```
transform /home/runner/work/jest-preset-angular/jest-preset-angular/examples/example-app-v13/node_modules/@angular/core/fesm2015/testing.mjs: 68.032ms
transform /home/runner/work/jest-preset-angular/jest-preset-angular/examples/example-app-v13/node_modules/@angular/core/fesm2015/core.mjs: 126.100ms
transform /home/runner/work/jest-preset-angular/jest-preset-angular/examples/example-app-v13/node_modules/@angular/compiler/fesm2015/compiler.mjs: 147.075ms
```
**With TypeScript transpileModule on Linux Node 12 no Jest cache**
```
transform /home/runner/work/jest-preset-angular/jest-preset-angular/examples/example-app-v13/node_modules/@angular/core/fesm2015/testing.mjs: 764.372ms
transform …
```

perf: use `esbuild` to process `.mjs` files

---

.github/dependabot.yml

Ignore all deps related to Jest and Angular from dependabot updates. These deps need to be manually updated. See reference https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#ignore
dependabot should not check update for these deps anymore.
**N.A.**

build(devs-infra): configure `dependabot` to ignore updating some deps

---

presets/index.d.ts

The type `TsJestPresets` is only a subset of Jest's `InitialOptions`-type:
https://github.com/kulshekhar/ts-jest/blob/c7ba4593ffdcc2bc81c1193863ab2941c3376976/src/types.ts#L46-L49
When e.g. accessing property `global` (as shown in the [documentation](https://thymikee.github.io/jest-preset-angular/docs/getting-started/presets/#advanced)) TS will complain, because it is not Part of `TsJestPresets`.

fix(presets): use jest types for exposed default options

---

src/ng-jest-transformer.spec.ts
src/ng-jest-transformer.ts

Instead of creating `ConfigSet` instances all the time (which is an expensive operation, as it involves path concatenations, merging configurations, reading from disk...), we use a private method in `ts-jest` that caches the configurations.
Kind of a follow-up to https://github.com/thymikee/jest-preset-angular/pull/1310 and inspired by the discussions in https://github.com/thymikee/jest-preset-angular/pull/1313.
This patch results in significant decrease in the execution time of our test harness: from 821s to 694s.
`npm test` is passing. Our test harness runs without any issues with this patch.

perf(transformer): leverage the ts-jest config set cache

---

src/ng-jest-transformer.ts

Since the result will be the same for all transformer instances we can cache the result, thus avoiding resolving and spawning redundant processes.
For a test harness with ~3800 tests grouped in ~110 projects this translates to a reduction in running time of ~20s. Attaching a screenshot of the profile that shows how instantiation takes ~20s.
The existing tests are passing (`npm test`). Our existing test harness runs without any issues with this patch.

perf(transformer): cache useNativeEsbuild result

---

package.json

Green CI
Angular 10 is no longer supported, see https://angular.io/guide/releases#support-policy-and-schedule The minimum support Angular version now is 11
**N.A.**

build: drop Angular 10 support

---

presets/index.js
src/config/__snapshots__/jest-preset.spec.ts.snap

Jest 28 correctly resolves Angular package format files so the `ng-jest-resolver` can be marked as optional
Green CI
**N.A.**

feat: exclude `ng-jest-resolver` from default/esm presets

---

package.json

This PR adds peer deps for jest and typescript, so yarn 3 does not complain about it missing in a normal angular workspace
This PR fixes #1441

fix: add missing jest and typescript to peer dep

---

presets/defaults-esm/jest-preset.d.ts
presets/defaults-esm/jest-preset.js
presets/defaults-esm/jest-preset.mjs
presets/defaults/jest-preset.d.ts
presets/index.js
src/presets/__snapshots__/index.spec.ts.snap
src/presets/index.spec.ts
src/presets/index.ts

Green CI
ESM preset now uses `.mjs` extensions which cannot use with `require` syntax if one is doing it.
**N.A.**

feat(presets): use `.mjs` extension for ESM preset

---

package.json

Allows to work with alpha, beta, rc etc.
CI/CD doesn't fail, no regressions
The plan is to avoid errors like:
```
npm WARN Found: @angular/compiler-cli@14.0.0-next.15
npm WARN Could not resolve dependency:
npm WARN peer @angular/compiler-cli@">=10.0.0" from jest-preset-angular@11.1.2
```

fix: supporting future unstable versions

---

examples/example-app-monorepo/apps/app1/jest-esm.config.mjs
examples/example-app-monorepo/apps/app1/setup-jest-esm.ts
examples/example-app-monorepo/apps/app1/setup-jest.ts
examples/example-app-monorepo/libs/user/jest-esm.config.mjs
examples/example-app-monorepo/libs/user/setup-jest-esm.ts
examples/example-app-monorepo/libs/user/setup-jest.ts
examples/example-app-v11/jest-esm.config.mjs
examples/example-app-v11/setup-jest-esm.ts
examples/example-app-v12/jest-esm.config.mjs
examples/example-app-v12/setup-jest-esm.ts
examples/example-app-v13/jest-esm.config.mjs
examples/example-app-v13/setup-jest-esm.ts
examples/example-app-v13/setup-jest.ts
examples/example-app-yarn-workspace/packages/angular-app/jest-esm.config.mjs
examples/example-app-yarn-workspace/packages/angular-app/setup-jest-esm.ts
examples/example-app-yarn-workspace/packages/angular-app/setup-jest.ts
examples/example-app-yarn-workspace/packages/user/jest-esm.config.mjs
examples/example-app-yarn-workspace/packages/user/setup-jest-esm.ts
examples/example-app-yarn-workspace/packages/user/setup-jest.ts
scripts/test-examples.js
setup-jest.js
setup-jest.mjs
src/config/setup-jest.spec.ts
tsconfig.json
website/docs/guides/angular-13+.md
website/docs/guides/esm-support.md

Add `setup-jest.mjs` for ESM mode and update documentation.
Revert #1429 
Green CI
**N.A.**

feat(config): add `setup-jest.mjs` for ESM mode

---

package.json

fix renovate bot to avoid npm install failures on Angular 14-next, and make pipelines green.
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: a14@0.0.0
npm ERR! Found: @angular-devkit/build-angular@14.0.0-next.13
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"14.0.0-next.13" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular-devkit/build-angular@">=0.1102.19 <14.0.0" from jest-preset-angular@12.0.0-next.2
npm ERR! node_modules/jest-preset-angular
npm ERR!   dev jest-preset-angular@"12.0.0-next.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or …
```

fix: supporting angular 14 alpha

---

.eslintrc.js
setup-jest.js
setup-jest.mjs
src/config/setup-jest.spec.ts
src/global.d.ts
tsconfig.json
website/docs/getting-started/test-environment.md

Users can configure `destroyAfterEach` via `globalThis` in the setup Jest file. For example
```
// setup-jest.ts
globalThis.ngJest = {
destroyAfterEach: true
}
import 'jest-preset-angular/setup-jest';
```
Closes #1466 
Green CI
**N.A.**

feat: allow configuring `destroyAfterEach` for setup test env

---

setup-jest.js
setup-jest.mjs
src/config/setup-jest.spec.ts
src/global.d.ts
website/docs/getting-started/test-environment.md

In  #1466 , I've forgotten to mention that there was a whole configuration object for the teardown options. 
People who passed the `destroyAfterEach` flag will need to pass the whole options object

feat: allow passing the whole ModuleTeardownOptions

---

setup-jest.js
setup-jest.mjs
src/config/setup-jest.spec.ts
src/global.d.ts
website/docs/getting-started/test-environment.md

Users can configure all TestEnvironmentOptions via globalThis in the setup Jest file. 
```
globalThis.ngJest = {
testEnvironmentOptions: {
teardown: {
destroyAfterEach: false,
rethrowErrors: true,
},
errorOnUnknownElements: true,
errorOnUnknownProperties: true,
},
};
```
closes #1656
N.A.

feat: allow configuring options for setup test env

---

website/docs/getting-started/options.md
website/versioned_docs/version-10.x/getting-started/options.md
website/versioned_docs/version-11.0/getting-started/options.md
website/versioned_docs/version-11.1/getting-started/options.md
website/versioned_docs/version-12.0/getting-started/options.md
website/versioned_docs/version-9.x/getting-started/options.md

Transform property doesn't explicitly mention SVG, but it is a file transform provided in the RegExp.
Update to the documentation to include SVG in the file transform config description, which is included in the preceding RegExp of the transform property in the example object literal.
None.  Documentation update.

Added SVG to transform config explanation

---

src/config/global-setup.ts

If someone wants to run another function before calling the global-setup, they can use a named export or a default export for importing the original global-setup function and calling it manually.
Jest already supports default exports for globalSetup functions, so no impact is expected.

Allows default and named export for global-setup

---

setup-jest.js
setup-jest.mjs
src/config/setup-jest.spec.ts
src/global.d.ts

Green CI
`destroyAfterEach` and `teardown` are no longer available to use, please use `testEnvironmentOptions` instead.
**N.A.**

feat: remove `destroyAfterEach` and `teardown` options

---

e2e/babel-support/package.json
e2e/babel-support/yarn.lock
e2e/jest-globals/package.json
e2e/jest-globals/yarn.lock
e2e/utils.ts
examples/example-app-monorepo/apps/app1/src/app/hero/hero-detail.component.spec.ts
examples/example-app-monorepo/package.json
examples/example-app-monorepo/yarn.lock
examples/example-app-v12/package.json
examples/example-app-v12/src/app/hero/hero-detail.component.spec.ts
examples/example-app-v12/yarn.lock
examples/example-app-v13/package.json
examples/example-app-v13/src/app/hero/hero-detail.component.spec.ts
examples/example-app-v13/yarn.lock
examples/example-app-v14/package.json
examples/example-app-v14/src/app/hero/hero-detail.component.spec.ts
examples/example-app-v14/yarn.lock
examples/example-app-yarn-workspace/packages/angular-app/package.json
examples/example-app-yarn-workspace/packages/angular-app/src/app/hero/hero-detail.component.spec.ts
examples/example-app-yarn-workspace/packages/user/package.json
examples/example-app-yarn-workspace/yarn.lock
package.json
src/__snapshots__/ng-jest-transformer.spec.ts.snap
src/presets/__snapshots__/index.spec.ts.snap
src/serializers/index.spec.ts
yarn.lock

There is a new Jest version out there and this package won't work with it unless the dependencies get updated. This package is the sole reason users of Angular currently still have to use Jest 28.

feat: support Jest 29

---

README.md
e2e/async/jest.config.js
src/config/ng-jest-config.spec.ts
src/config/ng-jest-config.ts
website/docs/getting-started/installation.md
website/versioned_docs/version-12.0/getting-started/installation.md

Related issue https://github.com/kulshekhar/ts-jest/issues/3822
Green CI
**N.A.**

feat(config): remove hardcoded logic setting `target` to `ES2015`

---

esbuild-check.js

During test debugging, I keep getting this exception:
```
Exception has occurred: Error: Expected "kind" to be "error" or "warning" in formatMessages() call
at Object.formatMessages2 [as formatMessages] (C:\Users\ADudek3\ra\cca-broker-addon-ui-old\node_modules\esbuild\lib\main.js:1469:13)
at C:\Users\ADudek3\ra\cca-broker-addon-ui-old\node_modules\esbuild\lib\main.js:2146:55
at new Promise (<anonymous>)
at Object.formatMessages (C:\Users\ADudek3\ra\cca-broker-addon-ui-old\node_modules\esbuild\lib\main.js:2146:14)
at Object.formatMessages (C:\Users\ADudek3\ra\cca-broker-addon-ui-old\node_modules\esbuild\lib\main.js:1959:70)
at Object.<anonymous> (C:\Users\ADudek3\ra\cca-broker-addon-ui-old\node_modules\jest-preset-angular\esbuild-check.js:4:4)
at Module._compile …
```

fix: typo in esbuild-check.js

---

e2e/snapshot-serializers/__tests__/__snapshots__/foo.component.spec.ts.snap
src/serializers/ng-snapshot.ts

removes `__ngContext__` from snapshots.
covered by foo component snapshot (see commit)
The existing snapshots need to be updated. However, with every subsequent change of the internal  `__ngContext__` attribute no change is necessary. 
Internal implemenation attribute pollutes the snapshots and should be removed.

#1815 remove __ngContext__ from snapshots

---

package.json
yarn.lock

Target angular 16

---

src/utils/ngcc-jest-processor.ts

This fixes #2073
- `git clone https://github.com/pal03377/jest-preset-angular` somewhere else
- `cd jest-preset-angular` from there
- `npm install`, then `npm run build`
- `npm link` to locally link this repo
- `cd path/to/minimal-example` from here https://github.com/pal03377/minimal-jest-pathsep-issue
- `npm install`, then `npm link jest-preset-angular`
- `npm run test` to verify that it now works

Fix: File separator issue on Windows causing error: jest: got error running globalsetup cannot find module @angular\compiler-cli

---

setup-jest.js
setup-jest.mjs
src/config/setup-jest.spec.ts
website/versioned_docs/version-11.0/guides/angular-13+.md
website/versioned_docs/version-11.1/guides/angular-13+.md

Close https://github.com/thymikee/jest-preset-angular/issues/2162
From zone.js 0.13.2, the original
`zone.js/bundles/zone-testing-bundle.js` is not easily import and will eventually removed from zone.js 0.14.0.
The proper way to import zone.js and zone.js/testing is
```
import 'zone.js';
import 'zone.js/testing';
```
So this PR use this way to import zone.js related bundles.

refactor: import zone.js/testing instead of zone-testing-bundle

---

package.json
yarn.lock

Angular 17 is being released sometime this week (Week of November 6th, 2023). This PR allows for users to install `jest-preset-angular` without getting `peerDependency` errors which cause some package managers to fail the install process.
We've tested `jest-preset-angular` + Angular 17 as part of the Angular 17 support for [Nx](https://github.com/nrwl/nx/pull/19689) and everything works other than a peer dependency error.

feat(deps): extend version support range to Angular 17

---

src/constants.ts
src/transformers/replace-resources.ts

With Angular v17, the `styles` property of the `Component` decorator additionally accepts a single string value instead of an array. Also, there's a new `styleUrl` property that accepts a single string value. The change was made at https://github.com/angular/angular/pull/51715.
This PR updates the transformer to handle the additional use cases and strip the properties accordingly. Without these changes, tests running over components that have those properties, fail.
I tested the fix as part of the Angular 17 support work in Nx. This particular PR https://github.com/nrwl/nx/pull/20146 is currently failing due to this issue. I tested the changes in this PR over those failing tests, and the failures are resolved.

fix(transformers): handle single string styles or styleUrl property

---

package.json
src/ngtsc/ts_compatibility/src/ts_cross_version_utils.ts
src/transformers/downlevel_decorators_transform/downlevel_decorators_transform.ts
src/transformers/replace-resources.ts
yarn.lock

I attempted to fix #2138, and as a side effect also upgrade to ng 17, resolving #2196. The main fixes were adding/improving the typescript version detection and version bridging functions so that the breaking changes in TS 5 (that I'm aware of) are handled, without changing the current level of backward compatibility with older versions of typescript and angular.
`yarn test` and `yarn test-examples` all pass (locally).
Tomorrow I will upgrade our projects to ng 17 and TS 5 to verify that our tests no longer hang, as described in #2138.
Should not be breaking - I did my best to preserve the existing level of backward compatibility.
fixes: #2138 
resolves: #2196

Fix TS5 + ESM hang; and upgrade dev dependencies to ng17

---

package.json

Minfies the JIT transformers, allowing for unused compiler parts to be elided, reducing
package size and speeding up execution

perf: reduce package size and speed up execution

---

website/docs/guides/angular-13+.md
website/versioned_docs/version-13.0/guides/angular-13+.md

This PR adds how to fix one issue when we are having Ionic 6 or 7 Framework in the project
We have to include this important configuration in the documentation so that all who are using Ionic 6 or 7 will avoid houuurs of investigation.
Error: 
Solution:
```js tab
module.exports = {
// ...other options
transformIgnorePatterns: ['<rootDir>/node_modules/(?!(@ionic/core|@ionic/angular|@stencil/core|.*\\.mjs$))']
};
```
- [ x ] No

Add extra configuration on jest.setup.js to support Ionic 6 or 7

---

package.json
yarn.lock

Angular 18 should be [released sometime this week](https://angular.dev/reference/releases#release-schedule) (the Week of November 20th, 2024). This PR allows users to install `jest-preset-angular` without getting `peerDependency` errors, which cause some package managers to fail the installation process.
We've tested `jest-preset-angular` + Angular 18 as part of [the Angular 18 support for Nx](https://github.com/nrwl/nx/pull/22509), and everything works other than a peer dependency error.
Additionally, I created a separate PR with a new example test application using the latest RC version of Angular 18: https://github.com/thymikee/jest-preset-angular/pull/2463. The CI checks are all passing. I'll update that PR when the stable version of Angular 18 is released.

feat: extend version support range to Angular 18

---

e2e/ng-jit-transformers/__tests__/replace-resource.spec.ts
e2e/ng-jit-transformers/bar.component.ts
src/transformers/replace-resources.ts

fix(transformers): handle template literals in styles or styleUrl property (#2735)

---

presets/index.js

DEPRECATION
Using `preset: 'jest-preset-angular'` is deprecated. The recommended approach is https://thymikee.github.io/jest-preset-angular/docs/getting-started/presets#createcjspresetoptions
Using `preset: 'jest-preset-angular/presets/defaults-esm'` is deprecated. The recommended approach is https://thymikee.github.io/jest-preset-angular/docs/getting-started/presets#createesmpresetoptions
**N.A.**

refactor: deprecate legacy presets

---

package.json

This update ensures compatibility for projects still using Angular 18 by removing the need to explicitly list the `@angular-devkit/build-angular` dependency. This is achieved by enabling the direct use of builders from `@angular/build`.

chore: 🤖 remove @angular-devkit/build-angular peerDep

---

presets/index.d.ts
src/presets/__snapshots__/index.spec.ts.snap

Since `jest-preset-angular/presets` is common js module types should be declared as `export = _defaults` instead of `export default _defaults`.
Currently require'ing reports not existing `createCjsPreset` function:
```js
const presets = require('jest-preset-angular/presets');
presets.createCjsPreset() // Property 'createCjsPreset' does not exist
```
Before:
```js
// jest.preset.js
const presets = require('jest-preset-angular/presets');
presets.createCjsPreset() // Property 'createCjsPreset' does not exist
```
After:
```js
// jest.preset.js
const presets = require('jest-preset-angular/presets');
presets.createCjsPreset() // Property 'createCjsPreset' exist
```

fix: properly handle types for presets module

---

package.json

Drop support for Node version lower than 18

---

src/__snapshots__/ng-jest-transformer.spec.ts.snap
src/config/ng-jest-config.spec.ts
tsconfig-base.spec.json
tsconfig.json

Green CI
`jest-preset-angular` artifacts are now built and shipped to `npm` targeting ES2022
**N.A.**

build: build package with target `es2022`

---

package.json
yarn.lock

- The minimum supported version for Angular is **18** following Angular support policy https://angular.dev/reference/releases#actively-supported-versions
- The minimum supported version for TypeScript is **5.5** following Angular 18
Green CI
**N.A.**

refactor: drop support for Angular 17

---

.github/actions/setup-docspace/action.yml
.github/workflows/audit.yml
.github/workflows/pr-docs-check.yml

Potential fix for [https://github.com/thymikee/jest-preset-angular/security/code-scanning/7](https://github.com/thymikee/jest-preset-angular/security/code-scanning/7)
To fix the problem, you should add a `permissions` block to the workflow. This can be done either at the root level (to apply to all jobs) or at the job level (to apply to a specific job). Since there is only one job (`deploy-preview`), adding it at the root is simplest and most maintainable. The minimal starting point is `contents: read`, but if the workflow needs to comment on pull requests or update their status, you may also need `pull-requests: write`. Based on the steps shown, the workflow likely only needs to read repository contents, so start with `contents: read`. If you later find that additional permissions are …

Potential fix for code scanning alert no. 7: Workflow does not contain permissions

---

package.json
website/docs/getting-started/installation.md
website/versioned_docs/version-14.x/getting-started/installation.md
website/versioned_docs/version-15.0/getting-started/installation.md
yarn.lock

Since Jest has validation for `jsdom` environment when `jest-environment-jsdom` doesn't exist, we can safely remove it.
Closes #3331

fix: remove peer dep `jest-environment-jsdom`
