circle.yml, example/package.json, jest-preset.json
=> Add ts coverage processor

jest-preset.json
Reference: http://facebook.github.io/jest/docs/getting-started.html#using-typescript
=> Add json as valid module exstension

HTMLElementPlugin.js, angular-snapshot.js, example/package.json, example/src/app/__snapshots__/app.component.spec.ts.snap, example/src/app/app.component.html, example/src/app/app.component.spec.ts, example/src/app/calc/__snapshots__/calc.component.spec.ts.snap, example/src/app/calc/calc.component.html, example/src/app/calc/calc.component.ts, package.json
**Summary**
Fixes #26.
Also, prepares for a bugfix in how snapshot serializers are invoked in Jest 20. 
As for now snapshots won't show Text nodes.
=> Remove ng version

example/yarn.lock, package.json, preprocessor.js, yarn.lock
=> Fix preprocessor (add transformOptions parameter with reasonable default)

example/package.json, example/src/app/app.component.spec.ts, example/yarn.lock, setupJest.js
=> Use universal zone.js instead of node-only

README.md
Noticed this was missing from the README, although it is in the [blog post](https://www.xfive.co/blog/testing-angular-faster-jest/) . I thought it would make sense to include this here too as well.
=> Update README to include installation instructions.

README.md
This comes up when using custom tsconfig files.
Resolves #93
=> Adds a warning about html transforms.

LICENSE, package.json
Change to MIT license according to issue License (MIT?) #88
=> Change to MIT license

example/src/app/service/hero.service.spec.ts, example/src/app/service/hero.service.ts, example/src/app/service/hero.ts, example/yarn.lock
I made an example of testing a service. The service will get data from a backend API. In case it fails to get data, it will use console.error to print the error. If it succeeds, it will use console.log to print the log. I have a problem of making code coverage for the constructor of the service. Maybe you can help me with that. Thank you.
=> Add an example of testing a service

__tests__/preprocessor.test.js, preprocessor.js
=> Fix `STYLE_URLS_REGEX` to not break on multiple new lines

__tests__/preprocessor.test.js, preprocessor.js
=> fix preprocess.js to not break on spaces before colon

package.json, yarn.lock
fixes short term https://github.com/thymikee/jest-preset-angular/issues/195
=> fix: restrict version of ts-jest to ~21.1.3

package.json
=> fix: moved @types/jest to devDependencies

CHANGELOG.md
I totally forgot we released new serializer in 7.1.0
cc @thymikee
=> Update changelog for v7.1.0

README.md
=> chore(docs): Clarified babel-jest dependencies requirements

README.md
To make it easier to get to the setup jest file, I've added a link.
=> Updated Readme.md with direct link to setup jest file

example/README.md
updating the README.md for the example project to indicate clearly where the jest config is
N/A
N/A
N/A
N/A
=> update README.md for example project

.dependabot/config.yml, README.md
=> Add Dependabot badge

.github/CODEOWNERS, .github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/question.md, .github/ISSUE_TEMPLATE/regression.md, .github/PULL_REQUEST_TEMPLATE.md, .github/SUPPORT.md
=> add github templates for issues and pull requests

src/InlineFilesTransformer.ts, src/StripStylesTransformer.ts, src/TransformUtils.ts, tsconfig.json
- Enable `importsNotUsedAsValues` tsconfig option.
- Enable a few other strict compiler options
Green CI
**N.A.**
=> chore(devs-infra): enable importsNotUsedAsValues tsconfig option

README.md
As far as I know, using ionic components in angular applications is a fairly common use case. There were a couple things I tripped on while getting jest set up to test my components that also contained ionic components, so I thought I would add them to the troubleshooting guide in case anyone else experiences the same.
N/A
N/A
=> chore(docs): add use of ionic components to troubleshooting section

.eslintignore, .eslintrc.js, .prettierrc, README.md, package.json, scripts/e2e.js, scripts/lib/logger.js, scripts/lib/paths.d.ts, scripts/lib/paths.js, src/AngularNoNgAttributesSnapshotSerializer.js, src/AngularSnapshotSerializer.js, src/HTMLCommentSerializer.js, src/InlineFilesTransformer.ts, src/StripStylesTransformer.ts, src/TransformUtils.ts, src/__tests__/InlineFilesTransformer.test.ts, src/__tests__/ReflectMetadata.test.ts, src/__tests__/StripStylesTransformer.test.ts, src/__tests__/__snapshots__/InlineFilesTransformer.test.ts.snap, src/__tests__/__snapshots__/StripStylesTransformer.test.ts.snap, src/reflect-metadata.ts, src/setup-jest.ts, src/zone-patch/index.js, tsconfig.build.json, tsconfig.json, yarn.lock
- Configure eslint based on recommended **eslint/typescript-eslint** config and disable a few rules which are not necessary.
- Upgrade typescript to 3.9.7 which requires our test snapshots to be updated.
- Update `README.md` because the restructure PR didn't update it.
Green CI
**N.A.**
=> build(devs-infra): configure eslint

.circleci/config.yml, README.md
- Remove badge from `README.md`
- Remove related commands from CircleCI config.
It seems like greenkeeper has been disconnected from our repository so I think we can skip that step.
Close #382
No more badge displays for `README` and CI shouldn't run any commands related to greenkeeper
**N.A.**
=> build(devs-infra): remove greenkeeper

package.json
Drop support for Angular < 8.0, see https://angular.io/guide/releases#support-policy-and-schedule
Green CI
**N.A.**
=> chore: follow Angular support policy

.github/dependabot.yml, package.json
- Setup dependabot config. This config is needed later when we use github actions (I think we should go for github actions)
- Correct wrong script for generating `CHANGELOG`.
**N.A.**
=> build(devs-infra): setup dependabot config for github actions

commitlint.config.js, package.json, yarn.lock
Switch to angular commit lint rule
No need to test
**N.A.**
=> build(devs-infra): switch to angular commit lint rules

README.md, e2e/test-app-v10-zone-v11/jest.config.js, e2e/test-app-v10/jest.config.js, e2e/test-app-v9/jest.config.js, jest-preset.js, jest.config.js
`ts-jest` will deprecate `tsConfig` in favor of `tsconfig`. This PR is to:
- Change all usages of `tsConfig` to `tsconfig`.
- Update `README` to instruct users to use `tsconfig` option.
Green CI
**N.A.**
=> refactor(presets): use `tsconfig` instead of `tsConfig` for `ts-jest`

CHANGELOG.md
=> chore(release): 8.3.2

README.md
=> chore(docs): redesign top part of README

e2e/test-app-v10-zone-v11/package.json, e2e/test-app-v10-zone-v11/src/app/app.component.spec.ts, e2e/test-app-v10-zone-v11/yarn.lock, e2e/test-app-v10/angular.json, e2e/test-app-v10/package.json, e2e/test-app-v10/projects/my-lib/README.md, e2e/test-app-v10/projects/my-lib/ng-package.json, e2e/test-app-v10/projects/my-lib/package.json, e2e/test-app-v10/projects/my-lib/src/lib/my-lib.component.spec.ts, e2e/test-app-v10/projects/my-lib/src/lib/my-lib.component.ts, e2e/test-app-v10/projects/my-lib/src/lib/my-lib.module.ts, e2e/test-app-v10/projects/my-lib/src/lib/my-lib.service.spec.ts, e2e/test-app-v10/projects/my-lib/src/lib/my-lib.service.ts, e2e/test-app-v10/projects/my-lib/src/public-api.ts, e2e/test-app-v10/projects/my-lib/tsconfig.lib.json, e2e/test-app-v10/projects/my-lib/tsconfig.lib.prod.json, e2e/test-app-v10/projects/my-lib/tsconfig.spec.json, e2e/test-app-v10/projects/my-lib/tslint.json, e2e/test-app-v10/src/app/app.component.spec.ts, e2e/test-app-v10/tsconfig.json, e2e/test-app-v10/tsconfig.spec.json, e2e/test-app-v10/yarn.lock, e2e/test-app-v9/package.json, e2e/test-app-v9/yarn.lock, package.json, scripts/e2e.js, yarn.lock
- Update e2e tests' dependencies
- Add an example of Angular library
- Switch `async` to `waitForAsync` since `async` is deprecated in favor of `waitForAsync`
- Add `webpack` as optional dep, add `@ngtools/webpack` as dev dep
Green CI
**N.A.**
=> build(test): update e2e tests

e2e/test-app-v10-zone-v11/tsconfig.spec.json, e2e/test-app-v10/tsconfig.spec.json, e2e/test-app-v9/tsconfig.spec.json, scripts/README.md
- Make all `tsconfig.spec.json` in e2e tests similar to each other and follow initiated Angular CLI generated `tsconfig.spec.json`.
- Update e2e `README.md`.
Green CI
**N.A.**
=> test(e2e): update e2e tsconfig.spec.json and e2e README

.github/workflows/release-and-publish.yml
Automatic release based on tag. How to do it:
- Create a tag in local. If a tag includes **rc/next**, action will publish under **next** tag otherwise action will publish under **latest** tag. For example:
+ v9.0.0-next.2/v9.0.0-rc.0: **next** tag
+ v9.0.0: **latest** tag
- Push the tag to upstream (https://github.com/thymikee/jest-preset-angular)
- Cheers 🥂 
This script is copied from `ts-jest` and it has been already verified working there.
**N.A.**
=> build(ci): add github action release and publish

e2e/test-app-v10-zone-v11/package.json, e2e/test-app-v10-zone-v11/src/app/custom-typings/index.spec.ts, e2e/test-app-v10-zone-v11/src/global.ts, e2e/test-app-v10-zone-v11/src/jquery.d.ts, e2e/test-app-v10-zone-v11/tsconfig.spec.json, e2e/test-app-v10-zone-v11/yarn.lock
Add custom typing e2e test
Green CI
**N.A.**
=> test(e2e): add custom typing e2e test

README.md
Add Table of Contents for `README.md`. This will make it easier for users to search for what they want.
**N.A.**
=> docs(devs-infra): add table of contents for `README.md`

tsconfig.build.json, yarn.lock
Ship package with target `es2015`. This is more inline with jest, see https://jestjs.io/blog/2020/05/05/jest-26 as well as Angular
Green CI
`jest-preset-angular` no longer ships with `es5` build but now with `es2015`
**N.A.**
=> build(devs-infra): build package with target `es2015`

src/__tests__/__snapshots__/ng-jest-compiler.spec.ts.snap, src/__tests__/index.spec.ts, src/__tests__/ng-jest-compiler.spec.ts, src/compiler/ng-jest-compiler.ts, src/index.ts
Support ESM for `isolatedModules: true`
Added unit test, green CI
**N.A.**
=> feat(compiler): allow `isolatedModules: true` to have ESM support

CHANGELOG.md, package.json
=> chore(release): 9.0.0-next.4

e2e/__tests__/forward-ref/forward-ref.spec.ts, e2e/test-app-v10/jest-cjs-iso.config.js, e2e/test-app-v10/jest-cjs-uniso.config.js, e2e/test-app-v10/jest-esm-iso.config.js, e2e/test-app-v10/jest.config.js, e2e/test-app-v10/package.json, e2e/test-app-v10/tsconfig-cjs.spec.json, e2e/test-app-v10/tsconfig-esm.spec.json, e2e/test-app-v10/tsconfig.spec.json, e2e/test-app-v11/jest-cjs-iso.config.js, e2e/test-app-v11/jest-cjs-uniso.config.js, e2e/test-app-v11/jest-esm-iso.config.js, e2e/test-app-v11/jest.config.js, e2e/test-app-v11/package.json, e2e/test-app-v11/tsconfig-cjs.spec.json, e2e/test-app-v11/tsconfig-esm.spec.json, e2e/test-app-v11/tsconfig.spec.json, e2e/test-app-v9/jest-cjs-iso.config.js, e2e/test-app-v9/jest-cjs-uniso.config.js, e2e/test-app-v9/jest-esm-iso.config.js, e2e/test-app-v9/jest.config.js, e2e/test-app-v9/package.json, e2e/test-app-v9/tsconfig-cjs.spec.json, e2e/test-app-v9/tsconfig-esm.spec.json, e2e/test-app-v9/tsconfig.spec.json, scripts/e2e.js, yarn.lock
Add separate E2E test configs for:
- `CJS` with `isolatedModules: false`
- `CJS` with `isolatedModules: true`
- `ESM` with `isolatedModules: true`
Green CI
**N.A.**
=> test(e2e): run ESM/CJS tests with isolatedModules true/false

e2e/test-app-v10/package.json, e2e/test-app-v11/package.json, e2e/test-app-v9/package.json, scripts/e2e.js
ESM support is not done yet. We discovered that there are issues with transformers not working with ESM
Green CI
**N.A.**
=> test(e2e): comment out wrong ESM e2e tests

jest.config.js, src/utils/ngcc-jest-processor.ts
As a part of ESM preparation
Green CI
**N.A.**
=> feat(utils): add `es2015` to `ngcc` script's properties

CHANGELOG.md, package.json
=> chore(release): 9.0.0-next.5

e2e/test-app-v10/package.json, e2e/test-app-v10/yarn.lock, e2e/test-app-v11/package.json, e2e/test-app-v11/yarn.lock, e2e/test-app-v9/package.json, e2e/test-app-v9/yarn.lock, package.json, yarn.lock
Upgrade e2e deps and remove unnecessary deps
Green CI
**N.A.**
=> build(deps-dev): upgrade e2e deps and remove unnecessary deps

src/__tests__/ng-jest-compiler.spec.ts, src/compiler/ng-jest-compiler.ts, yarn.lock
Prevent potential side effects by not overwriting the original compiler options which are resolved from tsconfig
Adjusted unit tests, green CI
**N.A.**
=> refactor(compiler): don't overwrite initial compiler options

package.json, yarn.lock
Upgrade `ts-jest@27.0.0-next.3`
Green CI
**N.A.**
=> build(devs-dep): upgrade ts-jest@27.0.0-next.3

CHANGELOG.md, package.json, yarn.lock
=> chore(release): 9.0.0-next.6

src/config/ng-jest-config.ts
The fallback is handled by `ts-jest` so we don't need to provide fallback
Green CI
**N.A.**
=> refactor(compiler): remove fallback for target after resolving tsconfig

package.json, src/__tests__/__snapshots__/ng-jest-compiler.spec.ts.snap, src/transformers/downlevel-ctor.ts, yarn.lock
Upgrade ng dev deps to v11
Green CI
**N.A.**
=> build(devs-dep): upgrade ng dev deps to v11

src/config/ng-jest-config.ts
The fallback is handled by `ts-jest`
Green CI
**N.A.**
=> refactor(config): remove fallback for module after resolving tsconfig

e2e/test-app-v9/package.json, e2e/test-app-v9/yarn.lock, package.json, src/compiler/ng-jest-compiler.ts, src/transformers/downlevel-ctor.ts, src/transformers/replace-resources.ts, yarn.lock
Adopt `ts-jest@27.0.0-next.5`
Green CI
**N.A.**
=> build(deps-dev): upgrade `ts-jest` to 27.0.0-next.5

e2e/__tests__/forward-ref/forward-ref.spec.ts, src/__tests__/__snapshots__/downlevel-ctor.spec.ts.snap, src/__tests__/downlevel-ctor.spec.ts, src/compiler/ng-jest-compiler.ts
Use constructor downlevel ctor transformer for `isolatedModules: true`
Green CI
**N.A.**
=> feat(compiler): use downlevel ctor for `isolatedModules: true`

e2e/test-app-v10/jest.config.js, e2e/test-app-v10/package.json, e2e/test-app-v11/jest.config.js, e2e/test-app-v11/package.json, e2e/test-app-v9/jest.config.js, e2e/test-app-v9/package.json, ngcc-jest-processor.js, scripts/e2e.js, src/utils/ngcc-jest-processor.ts
Add `ngcc-jest-processor` copied from `master`
Green CI
**N.A.**
=> feat: add `ngcc-jest-processor` util script

e2e/__tests__/jest-globals/jest-globals.test.ts, package.json, yarn.lock
Upgrade some deps and correct lint errors
Green CI
**N.A.**
=> build(devs-dep): upgrade deps

.github/dependabot.yml, .github/workflows/nodejs.yml
Disable dependabot because yarn 2 is not working with it yet, see https://github.com/dependabot/dependabot-core/issues/1297
Green CI
**N.A.**
=> build(devs-infra): disable dependabot

package.json
See https://nodejs.org/api/packages.html#packages_package_entry_points
Green CI
**N.A.**
=> build: add `exports` field to `package.json`

e2e/test-app-v10/jest-cjs-iso.config.js, e2e/test-app-v10/jest-esm-iso.config.js, e2e/test-app-v11/jest-cjs-iso.config.js, e2e/test-app-v11/jest-esm-iso.config.js, e2e/test-app-v9/jest-cjs-iso.config.js, e2e/test-app-v9/jest-esm-iso.config.js, package.json
Fix regression introduced by #893
Adjusted e2e jest config, green CI
**N.A.**
=> fix: define export path for `jest-preset`

e2e/ast-transformers/replace-resources/__tests__/bar.component.ts, e2e/tsconfig-esm.json, src/__tests__/__mocks__/foo.component.ts, src/__tests__/__mocks__/forward-ref.ts, src/__tests__/__snapshots__/downlevel-ctor.spec.ts.snap, src/__tests__/__snapshots__/replace-resources.spec.ts.snap, src/__tests__/downlevel-ctor.spec.ts, src/__tests__/replace-resources.spec.ts, src/transformers/replace-resources.ts, tsconfig.spec.json
Keep whatever in `Component` decorator `styles` property. This allows testing css for DOM elements via `window.getComputedStyle`
Added unit test, adjust e2e test
Green CI
**N.A.**
=> feat: allow css testing with `@Component` property `styles`

package.json, yarn.lock
Upgrade deps to be compatible with jest **next-8**
Green CI
**N.A.**
=> build(deps-dev): upgrade deps to be compatible with jest next-8

e2e/ast-transformers/replace-resources/__tests__/bar.component.ts, website/docs/guides/testing-css-styles.md, website/docs/guides/using-with-babel.md, website/sidebars.js, website/versioned_docs/version-8.x/guides/testing-css-styles.md, website/versioned_docs/version-8.x/guides/using-with-babel.md, website/versioned_sidebars/version-8.x-sidebars.json
Add a guide documentation for testing CSS styles
Green CI, a new entry in Guides section called **Testing CSS Styles** should be available for both doc **8.x** and **Next**
**N.A.**
=> docs(devs-infra): add documentation for testing styles

e2e/ast-transformers/replace-resources/__tests__/bar.component.ts, e2e/ast-transformers/replace-resources/jest-esm.config.js, e2e/ast-transformers/replace-resources/package.json, e2e/snapshot-serializers/jest-esm.config.js, e2e/snapshot-serializers/package.json, presets/index.js, src/__tests__/__snapshots__/jest-preset.spec.ts.snap, src/__tests__/__snapshots__/replace-resources.spec.ts.snap, src/transformers/replace-resources.ts, website/docs/guides/testing-css-styles.md
Revert #903 
This is because some syntaxes are not processed by Jest.
Green CI
**N.A.**
=> fix(transformers): revert #903 as some file extensions are not processed with their original content

package.json, yarn.lock
- adopt jest@27.0.0-next.9
- Upgrade other deps
Green CI
**N.A.**
=> build(devs-dep): adopt jest@27.0.0-next.9

examples/example-app-v10/package.json, examples/example-app-v10/yarn.lock, examples/example-app-v11/package.json, examples/example-app-v11/yarn.lock, examples/example-app-v9/package.json, examples/example-app-v9/yarn.lock, scripts/upgrade-examples-deps.js
Upgrade `examples` with latest release of the package.
Green CI
**N.A.**
=> build(devs-dep): upgrade example apps after publish

README.md, examples/example-app-v10/package.json, examples/example-app-v10/tsconfig.spec.json, examples/example-app-v11/tsconfig.spec.json, examples/example-app-v9/tsconfig.spec.json, website/docs/getting-started/installation.md, website/versioned_docs/version-8.x/getting-started/installation.md
- Add Ivy guidance and example apps link to `README`.
- Add missing `@types/jest` in installation instruction.
Green CI
**N.A.**
=> docs(devs-infra): add additional info to README and online doc

examples/example-app-v10/jest-esm.config.js, examples/example-app-v11/jest-esm.config.js, examples/example-app-v12/jest-esm.config.js, examples/example-app-v9/jest-esm.config.js, package.json
Closes #935
Updated jest config in `examples` to test package exports
**N.A.**
=> fix: add missing export `build` in `package.json`

CHANGELOG.md, website/docs/getting-started/options.md, website/versioned_docs/version-9.x/getting-started/options.md
Closes #938 
Green CI
**N.A.**
=> docs(devs-infra): update doc about remove `moduleNameMapper` config

website/docs/getting-started/installation.md, website/versioned_docs/version-8.x/getting-started/installation.md, website/versioned_docs/version-9.x/getting-started/installation.md
Closes #956 
Green CI
**N.A.**
=> docs(devs-infra): show content of `jest-global-mocks` in tip

package.json, yarn.lock
=> build: put `webpack` to optional peer dependency

src/utils/ngcc-jest-processor.ts
Add resolve path of `@angular/core` to error message when cannot find it
Green CI
**N.A.**
=> refactor(utils): improve `ngcc-jest-processor` error message

.github/ISSUE_TEMPLATE.md, .github/workflows/doc-generator.yml, .github/workflows/nodejs.yml, README.md, website/docs/getting-started/test-environment.md, website/docs/guides/jsdom-version.md, website/docusaurus.config.js, website/src/pages/versions.js, website/versioned_docs/version-8.x/guides/jsdom-version.md, website/versioned_docs/version-9.x/getting-started/test-environment.md, website/versioned_docs/version-9.x/guides/jsdom-version.md
- Configure GitHub workflows to use `main` instead of `master`
- Configure online doc to point to `main` instead of `master`
Green CI
**N.A.**
=> build(devs-infra): configure CI and doc to point to `main`

website/package.json, website/yarn.lock
=> docs(devs-infra): upgrade docusaurus deps

src/__tests__/ngcc-jest-processor.spec.ts, src/utils/ngcc-jest-processor.ts
Allow skipping `ngcc-jest-processor` via some Jest args
Added unit test
Green CI
**N.A.**
=> fix(utils): allow skipping `ngcc-jest-processor` via some Jest args

examples/example-app-v10/package.json, examples/example-app-v10/yarn.lock, examples/example-app-v11/package.json, examples/example-app-v11/yarn.lock, examples/example-app-v12-monorepo/package.json, examples/example-app-v12-monorepo/yarn.lock, examples/example-app-v12/package.json, examples/example-app-v12/yarn.lock, examples/example-app-yarn-workspace/packages/angular-app/package.json, examples/example-app-yarn-workspace/yarn.lock
Update `tslib` to **2.3.1** for all example apps in `examples` folder
Green CI
**N.A.**
=> build(devs-infra): update `tslib` to 2.3.1 for `examples`

.github/workflows/ci.yml, examples/example-app-v10/jest-esm.config.js, examples/example-app-v11/jest-esm.config.js, examples/example-app-v12-monorepo/projects/app1/jest-esm.config.js, examples/example-app-v12-monorepo/projects/app2/jest-esm.config.js, examples/example-app-v12/jest-esm.config.js, examples/example-app-yarn-workspace/packages/angular-app/jest-esm.config.js
=> test: update examples' ESM config

.github/workflows/ci.yml
=> build(devs-infra): use Node 16 for some CI steps

package.json
Green CI
New NodeJs range version support is ^12.20.0 || ^14.15.0 || >=16.10.0
**N.A.**
=> build: follow the latest Angular NodeJS range version support

website/package.json, website/yarn.lock
Upgrade `docusaurus` deps to `2.0.0-beta.9`
Green CI
**N.A.**
=> build(devs-dep): update docusaurus deps

README.md
Click on link should open page
**N.A.**
=> docs(devs-infra): correct link in `README`

.npmignore, scripts/test-examples.js
Closes #1133 
Run `npm pack` locally and then extract the `.tgz` file to see if `reflection/src` is included. Attached screenshot
**N.A.**
=> build(devs-infra): allow `reflection/src` to be in published content

src/__tests__/ng-snapshot.spec.ts, src/serializers/ng-snapshot.ts
Closes #1148
Added unit test
Green CI
**N.A.**
=> fix(serializers): revert partially changes in `ng-snapshot`

CHANGELOG.md, website/docs/getting-started/options.md, website/docs/guides/angular-13+.md
Closes #1149 
Green CI
**N.A.**
=> docs(devs-infra): update documentation about Angular 13 libraries

website/docs/guides/angular-13+.md, website/docs/guides/troubleshooting.md
Suggestion from https://github.com/thymikee/jest-preset-angular/issues/1147#issuecomment-963920524
Navigate to `website/` and start doc server with `yarn start` and go to http://localhost:3000/jest-preset-angular/docs/next/guides/angular-13+
**N.A.**
=> docs(devs-infra): update docs for possible issues in Angular 13

examples/example-app-v10/package.json, examples/example-app-v10/yarn.lock, examples/example-app-v11/package.json, examples/example-app-v11/yarn.lock, examples/example-app-v12-monorepo/package.json, examples/example-app-v12-monorepo/yarn.lock, examples/example-app-v12/package.json, examples/example-app-v12/yarn.lock, examples/example-app-v13/package.json, examples/example-app-v13/yarn.lock, examples/example-app-yarn-workspace/packages/angular-app/package.json, examples/example-app-yarn-workspace/yarn.lock
=> build(devs-dep): update example apps with rc.4 release

package.json, src/__tests__/jest-preset.spec.ts
=> test(unit): add unit test for `presets` types

package.json, yarn.lock
Closes #1191 
Green CI
**N.A.**
=> fix: add `bs-logger` as a direct dependency

e2e/babel-support/yarn.lock, e2e/custom-typings/package.json, e2e/custom-typings/yarn.lock, examples/example-app-v10/package.json, examples/example-app-v10/yarn.lock, examples/example-app-v11/package.json, examples/example-app-v11/yarn.lock, examples/example-app-v12-monorepo/package.json, examples/example-app-v12-monorepo/yarn.lock, examples/example-app-v12/package.json, examples/example-app-v12/yarn.lock, examples/example-app-v13/package.json, examples/example-app-v13/yarn.lock, scripts/prebuild.js
=> build(devs-dep): update `jest-preset-angular` for example apps

package.json, yarn.lock
=> build(deps-dep): upgrade `esbuild` to 0.14.2

.github/workflows/ci.yml, .github/workflows/doc-generator.yml
Use https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
Make a new push on this branch and observe in `Actions` tab if previous workflows are canceled.
**N.A.**
=> build: cancel previous workflows when new push on the branch happens

examples/example-app-v11/jest-esm.config.js, examples/example-app-v11/jest.config.js, examples/example-app-v12-monorepo/jest-esm.config.js, examples/example-app-v12-monorepo/jest.config.js, examples/example-app-v12-monorepo/projects/app1/jest-esm.config.js, examples/example-app-v12-monorepo/projects/app1/jest.config.js, examples/example-app-v12-monorepo/projects/app2/jest-esm.config.js, examples/example-app-v12-monorepo/projects/app2/jest.config.js, examples/example-app-v12/jest-esm.config.js, examples/example-app-v12/jest.config.js, examples/example-app-v13/jest-esm.config.js, examples/example-app-v13/jest.config.js, examples/example-app-yarn-workspace/packages/angular-app/jest-esm.config.js, examples/example-app-yarn-workspace/packages/angular-app/jest.config.js, global-setup.js, ngcc-jest-processor.js, scripts/test-examples.js, src/config/global-setup.ts, src/utils/ngcc-jest-processor.ts
Introduce a global setup script to fit with Jest architecture and deprecate `ngcc-jest-processor`
Green CI
**N.A.**
=> refactor: deprecate `ngcc-jest-processor` and replace with global setup

package.json, src/ng-jest-transformer.ts, yarn.lock
Closes #1255 
This can only be tested on a Windows machine with strict binary execution policy
**N.A.**
=> fix: support WASM-based esbuild optimizer fallback

e2e/babel-support/package.json, e2e/babel-support/yarn.lock, package.json, src/ng-jest-transformer.ts, yarn.lock
=> fix: apply similar fallback as Angular with `esbuild`

e2e/async/package.json, e2e/async/yarn.lock, e2e/babel-support/package.json, e2e/babel-support/yarn.lock, e2e/jest-globals/yarn.lock, examples/example-app-v11/package.json, examples/example-app-v11/yarn.lock, examples/example-app-v12-monorepo/package.json, examples/example-app-v12-monorepo/yarn.lock, examples/example-app-v12/package.json, examples/example-app-v12/yarn.lock, examples/example-app-v13/package.json, examples/example-app-v13/yarn.lock, examples/example-app-yarn-workspace/packages/angular-app/package.json, examples/example-app-yarn-workspace/yarn.lock, yarn.lock
=> build(devs-dep): upgrade project deps and e2e deps

website/docusaurus.config.js, website/package.json, website/src/pages/index.tsx, website/src/pages/versions.tsx, website/tsconfig.json, website/yarn.lock
Upgrade doc deps and switch to use TypeScript
Green CI
**N.A.**
=> docs(devs-infra): update deps and add typescript

examples/example-app-yarn-workspace/packages/angular-app/package.json, examples/example-app-yarn-workspace/yarn.lock, src/config/global-setup.spec.ts, src/config/global-setup.ts, src/utils/ngcc-jest-processor.ts, website/docs/getting-started/options.md, website/docs/guides/angular-13+.md, website/docs/guides/angular-ivy.md, website/versioned_docs/version-10.x/getting-started/options.md, website/versioned_docs/version-11.0/getting-started/options.md, website/versioned_docs/version-11.0/guides/angular-13+.md, website/versioned_docs/version-11.1/getting-started/options.md, website/versioned_docs/version-11.1/guides/angular-13+.md, website/versioned_docs/version-9.x/getting-started/options.md
Closes #1396 
Added unit test
Green CI
**N.A.**
=> feat: allow skip `ngcc` via `skipNgcc` option in Jest `globals`

src/config/global-setup.ts, src/utils/ngcc-jest-processor.ts
Closes #1348 
Green CI
**N.A.**
=> feat: allow running `ngcc` with specific `tsconfig` path

e2e/babel-support/package.json, e2e/babel-support/yarn.lock, e2e/jest-globals/package.json, e2e/jest-globals/yarn.lock, examples/example-app-v11/package.json, examples/example-app-v11/yarn.lock, examples/example-app-v12-monorepo/package.json, examples/example-app-v12-monorepo/yarn.lock, examples/example-app-v12/package.json, examples/example-app-v12/yarn.lock, examples/example-app-v13/package.json, examples/example-app-v13/yarn.lock, examples/example-app-yarn-workspace/packages/angular-app/package.json, examples/example-app-yarn-workspace/yarn.lock, package.json, scripts/update-e2e.js, src/compiler/ng-jest-compiler.spec.ts, src/compiler/ng-jest-compiler.ts, src/config/ng-jest-config.ts, src/ng-jest-transformer.ts, yarn.lock
=> build(devs-dep): set Jest's dependencies to 28

examples/example-app-v11/package.json, examples/example-app-v11/yarn.lock, examples/example-app-v12-monorepo/package.json, examples/example-app-v12-monorepo/yarn.lock, examples/example-app-v12/package.json, examples/example-app-v12/yarn.lock, examples/example-app-v13/package.json, examples/example-app-v13/yarn.lock, examples/example-app-yarn-workspace/packages/angular-app/package.json, examples/example-app-yarn-workspace/yarn.lock
=> test(examples): use `jest-preset-angular@12.0.0next-1`

src/config/setup-jest.spec.ts, src/config/setup-jest.ts
`setup-jest` now is identical to the file which is generated by Angular CLI for Karma + Jasmine, `test.ts`, in which `jest-preset-angular` put
```
import 'zone.js';
import 'zone.js/testing'
```
Green CI
**N.A.**
=> feat: use `import 'zone.js'` and `import 'zone.js/testing'`

examples/example-app-v12-monorepo/jest-esm-isolated.config.mjs, examples/example-app-v12-monorepo/jest-esm.config.mjs, scripts/test-examples.js
=> test(examples): enable ESM tests

jest.config.js, src/resolvers/ng-jest-resolver.spec.ts, src/resolvers/ng-jest-resolver.ts
=> refactor(resolver): use ts types from `jest-resolve`

examples/example-app-v11/src/app/app-services/app.service.ts, examples/example-app-v11/src/app/app-services/app.tokens.ts, examples/example-app-v11/src/app/app-services/index.ts, examples/example-app-v12-monorepo/projects/app1/src/app/app-services/app.service.ts, examples/example-app-v12-monorepo/projects/app1/src/app/app-services/app.tokens.ts, examples/example-app-v12-monorepo/projects/app1/src/app/app-services/index.ts, examples/example-app-v12-monorepo/projects/app2/src/app/app-services/app.service.ts, examples/example-app-v12-monorepo/projects/app2/src/app/app-services/app.tokens.ts, examples/example-app-v12-monorepo/projects/app2/src/app/app-services/index.ts, examples/example-app-v12/src/app/app-services/app.service.ts, examples/example-app-v12/src/app/app-services/app.tokens.ts, examples/example-app-v12/src/app/app-services/index.ts, examples/example-app-v13/src/app/app-services/app.service.ts, examples/example-app-v13/src/app/app-services/app.tokens.ts, examples/example-app-v13/src/app/app-services/index.ts, examples/example-app-yarn-workspace/packages/angular-app/src/app/app-services/app.service.ts, examples/example-app-yarn-workspace/packages/angular-app/src/app/app-services/app.tokens.ts, examples/example-app-yarn-workspace/packages/angular-app/src/app/app-services/index.ts
=> test(examples): add failed test cases

examples/example-app-v11/src/app/about/about.component.ts, examples/example-app-v11/src/app/app-services/app.service.spec.ts, examples/example-app-v11/src/app/shared/foo.component.spec.ts, examples/example-app-v11/src/app/shared/foo.component.ts, examples/example-app-v12-monorepo/projects/app1/src/app/about/about.component.ts, examples/example-app-v12-monorepo/projects/app1/src/app/app-services/app.service.spec.ts, examples/example-app-v12-monorepo/projects/app1/src/app/shared/foo.component.spec.ts, examples/example-app-v12-monorepo/projects/app1/src/app/shared/foo.component.ts, examples/example-app-v12-monorepo/projects/app2/src/app/about/about.component.ts, examples/example-app-v12-monorepo/projects/app2/src/app/app-services/app.service.spec.ts, examples/example-app-v12-monorepo/projects/app2/src/app/shared/foo.component.spec.ts, examples/example-app-v12-monorepo/projects/app2/src/app/shared/foo.component.ts, examples/example-app-v12/src/app/about/about.component.ts, examples/example-app-v12/src/app/app-services/app.service.spec.ts, examples/example-app-v12/src/app/shared/foo.component.spec.ts, examples/example-app-v12/src/app/shared/foo.component.ts, examples/example-app-v13/src/app/about/about.component.ts, examples/example-app-v13/src/app/app-services/app.service.spec.ts, examples/example-app-v13/src/app/shared/foo.component.spec.ts, examples/example-app-v13/src/app/shared/foo.component.ts, examples/example-app-yarn-workspace/packages/angular-app/src/app/about/about.component.ts, examples/example-app-yarn-workspace/packages/angular-app/src/app/app-services/app.service.spec.ts, examples/example-app-yarn-workspace/packages/angular-app/src/app/shared/foo.component.spec.ts, examples/example-app-yarn-workspace/packages/angular-app/src/app/shared/foo.component.ts
=> test(examples): add skipped tests for failed test cases

website/docs/guides/esm-support.md, website/versioned_docs/version-10.x/guides/esm-support.md, website/versioned_docs/version-11.0/guides/esm-support.md, website/versioned_docs/version-11.1/guides/esm-support.md, website/versioned_docs/version-12.0/guides/esm-support.md, website/versioned_docs/version-9.x/guides/esm-support.md
Closes #1465
Green CI
**N.A.**
=> docs(devs-infra): update ESM doc

website/docs/guides/troubleshooting.md, website/versioned_docs/version-10.x/guides/troubleshooting.md, website/versioned_docs/version-11.0/guides/troubleshooting.md, website/versioned_docs/version-11.1/guides/troubleshooting.md, website/versioned_docs/version-12.0/guides/troubleshooting.md, website/versioned_docs/version-8.x/guides/troubleshooting.md, website/versioned_docs/version-9.x/guides/troubleshooting.md
Closes #1472
Green CI
**N.A.**
=> docs(devs-infra): update `TROUBLESHOOTING` doc

package.json
Closes #1410
Green CI
**N.A.**
=> feat: support Angular 14

esbuild-check.js, src/ng-jest-transformer.ts
=> fix: add esbuild check to fallback to WASM if needed

examples/example-app-monorepo/jest-esm-isolated.config.mjs, examples/example-app-monorepo/jest-esm.config.mjs, examples/example-app-v12/jest-esm.config.mjs, examples/example-app-v13/jest-esm.config.mjs, examples/example-app-v14/jest-esm.config.mjs, examples/example-app-yarn-workspace/packages/angular-app/jest-esm.config.mjs, examples/example-app-yarn-workspace/packages/user/jest-esm.config.mjs, global-setup.js, global-setup.mjs, scripts/test-examples.js, src/config/global-setup.spec.ts, src/config/global-setup.ts
=> feat: add `global-setup.mjs` to use with Jest ESM mode

scripts/prebuild.js
Angular's repo recently updates the codes related to downlevel ctor. This causes build failure. 
This MR is to fix that problem.
Green CI
**N.A.**
=> build(devs-infra): adopt changes related to transformer deps' locations

.eslintrc.js, examples/example-app-v14/package.json, examples/example-app-v14/yarn.lock, package.json, src/transformers/replace-resources.ts, yarn.lock
Fixes #1732 
Green CI
**N.A.**
=> fix(transformers): adopt ts 4.8 changes for `replace-resource`

website/docs/getting-started/installation.md, website/versioned_docs/version-10.x/getting-started/installation.md, website/versioned_docs/version-11.0/getting-started/installation.md, website/versioned_docs/version-11.1/getting-started/installation.md, website/versioned_docs/version-12.0/getting-started/installation.md, website/versioned_docs/version-8.x/getting-started/installation.md, website/versioned_docs/version-9.x/getting-started/installation.md
This is the fix of the typo in the docs.
No need.
N/A.
=> Fix typo in docs (stimulate to simulate)

package.json, yarn.lock
Green CI
Minimum supported Angular version is 12
**N.A.**
=> feat: drop support for Angular 11

package.json, yarn.lock
Fixes #1773 
Green CI
**N.A.**
=> fix: add `jest-util` to list of `dependencies`

examples/example-app-monorepo/package.json, examples/example-app-monorepo/yarn.lock, examples/example-app-v13/package.json, examples/example-app-v13/yarn.lock, examples/example-app-v14/package.json, examples/example-app-v14/yarn.lock, examples/example-app-v15/package.json, examples/example-app-v15/yarn.lock, examples/example-app-yarn-workspace/packages/angular-app/package.json, examples/example-app-yarn-workspace/packages/user/package.json, examples/example-app-yarn-workspace/yarn.lock
=> build(devs-dep): upgrade dependencies for example apps

README.md
Update the angular version in the examples section of the README.md
Fixes the information in README.md
No need for tests.
=> docs: update angular version in readme

src/utils/ngcc-jest-processor.ts
Make ngcc processing optional.
- Run ngcc for Angular < 16
- Skip ngcc for Angular >= 16
fixes #1987 
related #2058
related #2061
Used patched jest-preset-angular in local Angular 16 project.
=> feat(utils): skip ngcc processing in ng16 or higher

CHANGELOG.md, package.json
=> chore(release): 13.1.0

package.json, yarn.lock
=> fix: revert drop support Angular 13, 14

e2e/ast-transformers/ng-jit-transformers/__tests__/signal-queries.spec.ts
**v17.2** requires us to publish a new version with new build assets. This PR only adds extra e2e tests to prove that the new build works with signal queries like `viewChild`
Closes #2315 
Green CI
**N.A.**
=> feat: support signal queries in Angular 17.2

examples/example-app-monorepo/apps/app1/jest-global-mocks.ts, examples/example-app-monorepo/libs/user/jest-global-mocks.ts, examples/example-app-v15/jest-global-mocks.ts, examples/example-app-v17/jest-global-mocks.ts, examples/example-app-yarn-workspace/packages/angular-app/jest-global-mocks.ts, examples/example-app-yarn-workspace/packages/user/jest-global-mocks.ts, website/docs/getting-started/installation.md, website/versioned_docs/version-10.x/getting-started/installation.md, website/versioned_docs/version-11.0/getting-started/installation.md, website/versioned_docs/version-11.1/getting-started/installation.md, website/versioned_docs/version-12.0/getting-started/installation.md, website/versioned_docs/version-13.0/getting-started/installation.md, website/versioned_docs/version-8.x/getting-started/installation.md, website/versioned_docs/version-9.x/getting-started/installation.md
closes: https://github.com/thymikee/jest-preset-angular/issues/2366
=> docs: CSS module should be set to undefined

examples/example-app-v17/src/app/dashboard/dashboard-hero.component.spec.ts, examples/example-app-v17/src/app/dashboard/dashboard-hero.component.ts, examples/example-app-v17/src/app/demo/demo.testbed.spec.ts, examples/example-app-v17/src/app/demo/demo.ts, examples/example-app-v17/src/app/shared/canvas.component.ts
=> test: update example app v17 with signals' usages

CHANGELOG.md, package.json
Closes #2392 
Closes #2374
Closes #2370
=> chore(release): 14.0.4

examples/example-app-monorepo/apps/app1/src/app/banner/__snapshots__/banner.component.spec.ts.snap, examples/example-app-monorepo/apps/app1/src/app/banner/banner.component.spec.ts, examples/example-app-monorepo/package.json, examples/example-app-v15/jest-esm.config.mjs, examples/example-app-v15/jest.config.js, examples/example-app-v15/src/app/banner/__snapshots__/banner.component.spec.ts.snap, examples/example-app-v15/src/app/banner/banner.component.spec.ts, examples/example-app-v17/jest-esm.config.mjs, examples/example-app-v17/jest.config.js, examples/example-app-v17/src/app/banner/__snapshots__/banner.component.spec.ts.snap, examples/example-app-v17/src/app/banner/banner.component.spec.ts, examples/example-app-yarn-workspace/packages/angular-app/jest.config.js, examples/example-app-yarn-workspace/packages/angular-app/src/app/banner/__snapshots__/banner.component.spec.ts.snap, examples/example-app-yarn-workspace/packages/angular-app/src/app/banner/banner.component.spec.ts, examples/example-app-yarn-workspace/packages/user/jest.config.js, src/serializers/ng-snapshot.ts
See commits
Closes #2124 
Green CI
**N.A.**
=> feat: remove ivy flag for snapshot serializer

examples/example-app-monorepo/apps/app1/src/app/app-services/app.service.spec.ts, examples/example-app-monorepo/apps/app1/src/app/app-services/app.service.ts, examples/example-app-monorepo/apps/app1/src/app/shared/foo.component.spec.ts, examples/example-app-monorepo/apps/app1/src/app/shared/foo.component.ts, examples/example-app-v15/src/app/app-services/app.service.spec.ts, examples/example-app-v15/src/app/app-services/app.service.ts, examples/example-app-v15/src/app/shared/foo.component.spec.ts, examples/example-app-v15/src/app/shared/foo.component.ts, examples/example-app-v17/src/app/app-services/app.service.spec.ts, examples/example-app-v17/src/app/app-services/app.service.ts, examples/example-app-v17/src/app/shared/foo.component.spec.ts, examples/example-app-v17/src/app/shared/foo.component.ts, examples/example-app-yarn-workspace/packages/angular-app/src/app/app-services/app.service.spec.ts, examples/example-app-yarn-workspace/packages/angular-app/src/app/app-services/app.service.ts, examples/example-app-yarn-workspace/packages/angular-app/src/app/shared/foo.component.spec.ts, examples/example-app-yarn-workspace/packages/angular-app/src/app/shared/foo.component.ts, website/docs/guides/troubleshooting.md, website/versioned_docs/version-13.0/guides/troubleshooting.md
cc @Coly010 
Green CI
**N.A.**
=> Add docs and examples about workaround for `@Inject`

e2e/async/package.json, e2e/async/yarn.lock, package.json, yarn.lock
=> build: upgrade to ng 18

setup-jest.js, setup-jest.mjs, src/config/setup-jest.spec.ts
fixes #1914
fixes #2514
Green CI
**N.A.**
=> feat: add polyfill for TextEncoder

examples/example-app-v15/README.md
The README for the v15 example was still mentioning the v14.
=> Update README.md on example-app-v15

e2e/snapshot-serializers/__tests__/__snapshots__/foo.component.spec.ts.snap, e2e/snapshot-serializers/__tests__/foo.component.html, src/serializers/no-ng-attributes.ts
Original from #2164  thanks @wellwind
**N.A.**
=> fix(serializers): generated `id="root{n}"` should be removed

src/serializers/no-ng-attributes.ts
=> refactor(serializers): improve codes for snapshot serializer

examples/example-app-monorepo/package.json, examples/example-app-monorepo/yarn.lock, examples/example-app-v15/package.json, examples/example-app-v15/yarn.lock, examples/example-app-v17/package.json, examples/example-app-v17/yarn.lock, examples/example-app-v18/package.json, examples/example-app-v18/yarn.lock, examples/example-app-yarn-workspace/packages/angular-app/package.json, examples/example-app-yarn-workspace/packages/user/package.json, examples/example-app-yarn-workspace/yarn.lock
=> Upgrade deps for example apps

package.json, yarn.lock
=> build(deps-dev): upgrade typescript to 5.5.3

src/compiler/ng-jest-compiler.spec.ts, src/compiler/ng-jest-compiler.ts
=> fix: load ts lib files to properly transform constructor for `isolatedModules: true`

jest-cjs.config.ts, jest-esm.config.ts, jest-transpile-cjs.config.ts, jest-transpile-esm.config.ts, setup-e2e-test.ts, tsconfig.eslint.json
=> test: add `setup-e2e-test.ts` to avoid repeating setup codes

CHANGELOG.md, package.json
=> chore(release): 14.2.4

CHANGELOG.md, README.md
=> fix typos for `CHANGELOG` and update `README`

.gitignore, src/__snapshots__/ng-jest-transformer.spec.ts.snap, src/ng-jest-transformer.spec.ts, src/ng-jest-transformer.ts, tsconfig.json
=> fix: include `version` from `package.json` into cache key

.editorconfig, e2e/zoneless-env/__tests__/zoneless-env.spec.ts, e2e/zoneless-env/foo.component.html, e2e/zoneless-env/foo.component.scss, e2e/zoneless-env/foo.component.ts, e2e/zoneless-env/jest-cjs.config.ts, e2e/zoneless-env/jest-esm.config.ts, e2e/zoneless-env/jest-transpile-cjs.config.ts, e2e/zoneless-env/jest-transpile-esm.config.ts, e2e/zoneless-env/setup-zoneless-env.mts, e2e/zoneless-env/setup-zoneless-env.ts, e2e/zoneless-env/tsconfig-cjs.spec.json, e2e/zoneless-env/tsconfig-esm.spec.json, setup-env/utils.js, setup-env/zone/index.js, setup-env/zone/index.mjs, setup-env/zoneless/index.js, setup-env/zoneless/index.mjs, setup-jest.js, setup-jest.mjs, src/config/setup-jest.spec.ts, website/docs/getting-started/test-environment.md, website/versioned_docs/version-14.3/getting-started/test-environment.md
=> feat: support config zoneless env for CJS

examples/example-app-monorepo/apps/app1/jest-esm.config.ts, examples/example-app-monorepo/apps/app1/jest.config.ts, examples/example-app-monorepo/libs/user/jest-esm.config.ts, examples/example-app-monorepo/libs/user/jest.config.ts, examples/example-app-v17/jest-esm.config.ts, examples/example-app-v17/jest.config.ts, examples/example-app-v18/jest-esm.config.ts, examples/example-app-v18/jest.config.ts, examples/example-app-v19/jest-esm.config.ts, examples/example-app-v19/jest.config.ts, examples/example-app-yarn-workspace/packages/angular-app/jest-esm.config.ts, examples/example-app-yarn-workspace/packages/angular-app/jest.config.ts, examples/example-app-yarn-workspace/packages/user/jest-esm.config.ts, examples/example-app-yarn-workspace/packages/user/jest.config.ts, examples/example-app-yarn-workspace/packages/user/package.json, examples/example-app-yarn-workspace/yarn.lock, jest-preset.js, presets/index.d.ts, presets/index.js, src/presets/__snapshots__/index.spec.ts.snap, src/presets/create-cjs-preset.ts, src/presets/create-esm-preset.ts, src/presets/index.spec.ts, src/presets/index.ts, src/presets/utils.ts, website/docs/getting-started/presets.md
=> feat: add preset creator functions

website/docs/getting-started/installation.md, website/versioned_docs/version-14.3/getting-started/installation.md, website/versioned_docs/version-14.4/getting-started/installation.md
Closes #2905 
Green CI
**N.A.**
=> docs: update `installation` doc

src/utils/ngcc-jest-processor.ts, website/docs/guides/angular-ivy.md
=> refactor: deprecate `ngcc` util via `globalSetup`

examples/example-app-monorepo/apps/app1/jest-isolated.config.ts, examples/example-app-monorepo/libs/user/jest-isolated.config.ts, examples/example-app-v17/jest-isolated.config.ts, examples/example-app-v18/jest-isolated.config.ts, examples/example-app-v19/jest-isolated.config.ts, examples/example-app-yarn-workspace/packages/angular-app/jest-isolated.config.ts, examples/example-app-yarn-workspace/packages/user/jest-isolated.config.ts, presets/index.js
=> refactor: deprecate `defaultTransformerOptions` in `presets`

examples/example-app-monorepo/apps/app1/jest-esm.config.ts, examples/example-app-monorepo/apps/app1/src/app/shared/foo.component.spec.ts, examples/example-app-monorepo/apps/app1/src/app/shared/foo.component.ts, examples/example-app-monorepo/libs/user/jest-esm.config.ts, examples/example-app-monorepo/package.json, examples/example-app-v17/jest-esm.config.ts, examples/example-app-v17/package.json, examples/example-app-v17/src/app/shared/foo.component.spec.ts, examples/example-app-v17/src/app/shared/foo.component.ts, examples/example-app-v18/jest-esm.config.ts, examples/example-app-v18/package.json, examples/example-app-v18/src/app/shared/app.service.ts, examples/example-app-v18/src/app/shared/foo.component.spec.ts, examples/example-app-v18/src/app/shared/foo.component.ts, examples/example-app-v19/jest-esm.config.ts, examples/example-app-v19/package.json, examples/example-app-v19/src/app/shared/foo.component.spec.ts, examples/example-app-v19/src/app/shared/foo.component.ts, examples/example-app-yarn-workspace/package.json, examples/example-app-yarn-workspace/packages/angular-app/jest-esm.config.ts, examples/example-app-yarn-workspace/packages/angular-app/package.json, examples/example-app-yarn-workspace/packages/angular-app/src/app/shared/foo.component.spec.ts, examples/example-app-yarn-workspace/packages/angular-app/src/app/shared/foo.component.ts, examples/example-app-yarn-workspace/packages/user/jest-esm.config.ts, examples/example-app-yarn-workspace/packages/user/package.json, website/docs/guides/esm-support.md, website/versioned_docs/version-14.5/guides/esm-support.md
See commits
Closes #2726 
**N.A.**
=> docs: update esm doc with moduleNameMapper

e2e/process-js-packages/__tests__/process-js-packages.spec.ts, e2e/process-js-packages/jest-cjs.config.ts, e2e/process-js-packages/jest-transpile-cjs.config.ts, e2e/process-js-packages/package.json, e2e/process-js-packages/yarn.lock, src/ng-jest-transformer.spec.ts, src/ng-jest-transformer.ts
See commits
Fixes #2913 
Green CI
**N.A.**
=> fix: transform `js` ESM file from `node_modules`

CHANGELOG.md, package.json
=> chore(release): 14.5.3

examples/example-app-monorepo/package.json, examples/example-app-monorepo/yarn.lock, examples/example-app-v19/package.json, examples/example-app-v19/yarn.lock, examples/example-app-yarn-workspace/packages/angular-app/package.json, examples/example-app-yarn-workspace/packages/user/package.json, examples/example-app-yarn-workspace/yarn.lock, package.json, website/package.json, website/yarn.lock, yarn.lock
=> build: bump to ts 5.7

src/compiler/ng-jest-compiler.ts
=> fix: warn when using both isolatedModules and emitDecoratorMetadata

.github/workflows/doc_ci.yml, .github/workflows/source_code_ci.yml, performance/__tests__/perf.spec.ts, performance/jest.config.ts, performance/package.json, performance/yarn.lock
=> infra: improve GH workflows

.github/workflows/source_code_ci.yml
=> ci: add Node 22 to workflow

.github/workflows/docs-deploy.yml, .github/workflows/pr-docs-check.yml
=> ci: add permission to deploy to GH pages

e2e/dynamic-import-in-mjs/__test_modules__/a.mjs, e2e/dynamic-import-in-mjs/__test_modules__/b.mjs, e2e/dynamic-import-in-mjs/__tests__/dynamic-import-in-mjs.spec.ts, e2e/dynamic-import-in-mjs/jest-cjs.config.ts, e2e/dynamic-import-in-mjs/jest-esm.config.ts, e2e/dynamic-import-in-mjs/jest-transpile-cjs.config.ts, e2e/dynamic-import-in-mjs/jest-transpile-esm.config.ts, e2e/dynamic-import-in-mjs/tsconfig-cjs.spec.json, e2e/dynamic-import-in-mjs/tsconfig-esm.spec.json, e2e/dynamic-import-in-mjs/tsconfig-transpile-cjs.spec.json, e2e/dynamic-import-in-mjs/tsconfig-transpile-esm.spec.json, src/__snapshots__/ng-jest-transformer.spec.ts.snap, src/ng-jest-transformer.ts
Added a new field 'dynamic-import' to the esbuild call to transform dynamic imports.
Closes #3368
=> fix: add `dynamic-import` support flag into esbuild invocation
